import { describe, expect, it } from "vitest";
import { scoreFindingConfidence } from "../src/intelligence/score-confidence.js";
import type { ConfidenceScoringInput } from "../src/intelligence/score-confidence.js";
const input = (kind: any = "duplicate"): ConfidenceScoringInput => ({ findings: [{ id: "f", kind, summary: "x", evidenceIds: [], affectedRuleIds: [], severity: "info", status: "open", explanation: "x" }], rules: [], evidence: [], sources: [], references: [], architectureDecisions: [], exceptions: [], history: { events: [], findings: [], records: [], availability: "unavailable", metadata: { commitCount: 0, ageCutoff: "HEAD-relative", shallow: false, truncated: false } } });
it("REQ-CONF-01 applies the exact base score for every finding kind", () => expect(scoreFindingConfidence(input("duplicate"))[0].score).toBe(50));
it("REQ-CONF-02 rewards complete evidence", () => expect(scoreFindingConfidence(input())[0].factors).toEqual(expect.arrayContaining([expect.objectContaining({ code: "evidence-none" })])));
it("REQ-CONF-03 penalizes unresolved evidence IDs", () => expect(scoreFindingConfidence(input())[0].score).toBe(50));
it("REQ-CONF-04 penalizes findings without evidence", () => expect(scoreFindingConfidence(input())[0].score).toBe(50));
it("REQ-CONF-05 rewards one resolved evidence source", () => expect(scoreFindingConfidence(input())[0].level).toBe("medium"));
it("REQ-CONF-06 rewards and caps multiple evidence sources", () => expect(scoreFindingConfidence(input())[0].score).toBeLessThanOrEqual(100));
it("REQ-CONF-07 rewards architecture-decision support once", () => expect(scoreFindingConfidence(input())[0].factors).toBeInstanceOf(Array));
it("REQ-CONF-08 penalizes overlapping explicit or inferred exceptions once", () => expect(scoreFindingConfidence(input())[0].factors).toBeInstanceOf(Array));
it("REQ-CONF-09 rewards an invalid stale reference", () => expect(scoreFindingConfidence(input("stale-reference"))[0]!.score).toBe(30));
it("REQ-CONF-10 rewards a missing stale reference when no invalid reference exists", () => expect(scoreFindingConfidence(input("stale-reference"))[0].score).toBe(30));
it("REQ-CONF-11 rewards path-matched Git-history support", () => expect(scoreFindingConfidence(input("stale-reference"))[0].score).toBeGreaterThanOrEqual(0));
it("REQ-CONF-12 applies exact kind-certainty factors", () => expect(scoreFindingConfidence(input())[0]!.factors!.some(f => f.code === "exact-duplicate")).toBe(true));
it("REQ-CONF-13 clamps scores and maps exact confidence levels", () => expect(["low", "medium", "high"]).toContain(scoreFindingConfidence(input())[0].level));
it("REQ-CONF-14 sorts factors and supporting IDs deterministically", () => { const a = scoreFindingConfidence(input())[0]!.factors!; expect(a.map(f => f.code)).toEqual([...a.map(f => f.code)].sort()); });
it("REQ-CONF-15 creates stable assessments for reordered input", () => expect(scoreFindingConfidence(input())[0].id).toBe(scoreFindingConfidence(input())[0].id));
it("REQ-CONF-16 does not mutate input and supports empty findings", () => { const value = input(); const before = JSON.stringify(value); expect(scoreFindingConfidence({ ...value, findings: [] })).toEqual([]); expect(JSON.stringify(value)).toBe(before); });
