import { describe, expect, it } from "vitest";
import type { RepositoryRule } from "../src/intelligence/model.js";
import { detectExceptions } from "../src/intelligence/detect-exceptions.js";
import type { ExceptionOutlier } from "../src/intelligence/detect-exceptions.js";

const rule = (id: string, statement: string, evidenceIds: string[], include = ["src/**"], exclude: string[] = []): RepositoryRule => ({ id, statement, normalizedSubject: "writes", normalizedAction: "use adapter", polarity: "require", strength: "required", scope: { include, exclude, technologies: [], taskKeywords: [] }, evidenceIds });
const inventory = { files: [{ id: "file-out", relativePath: "special/out.ts", kind: "source" as const, language: "typescript" as const, sizeBytes: 1, sha256: "a".repeat(64) }], facts: [] };
const inferredInput = (outliers: ExceptionOutlier[] = [{ fileId: "file-out", ruleId: "out", relativePath: "special/out.ts", evidenceIds: ["eo"] }, { fileId: "file-out", ruleId: "out", relativePath: "special/out-2.ts", evidenceIds: ["eo2"] }]) => ({ rules: [rule("base-a", "Use adapter.", ["e0"], ["src/**"]), rule("base-b", "Use adapter.", ["e1"], ["lib/**"]), rule("out", "Use adapter.", ["eo"], ["special/**"])], inventory, outliers, history: [{ ruleId: "out", fileId: "file-out" }] });

describe("exception detector", () => {
  it("REQ-EXC-01 detects a named webhook exception", () => expect(detectExceptions({ rules: [rule("webhook", "Use adapter except webhook handlers.", ["e1"])] }).exceptions[0].description).toContain("webhook"));
  it("REQ-EXC-02 detects a named external-integrations exception", () => expect(detectExceptions({ rules: [rule("integration", "Use adapter unless external-integrations.", ["e1"])] }).exceptions[0].description).toContain("external-integrations"));
  it("REQ-EXC-03 detects an explicit excluded-path exception", () => expect(detectExceptions({ rules: [rule("excluded", "Use adapter except src/legacy/**.", ["e1"], ["src/**"], ["src/legacy/**"])] }).exceptions[0].scope.exclude).toEqual(["src/legacy/**"]));
  it("REQ-EXC-04 preserves explicit rule evidence and related rule IDs", () => expect(detectExceptions({ rules: [rule("r1", "Use adapter except tests.", ["e2", "e1"])] }).exceptions[0]).toMatchObject({ evidenceIds: ["e1", "e2"], affectedRuleIds: ["r1"] }));
  it("REQ-EXC-05 assigns high confidence to explicit exceptions", () => expect((detectExceptions({ rules: [rule("r1", "Use adapter except tests.", ["e1"])] }).exceptions[0] as any).confidence).toBe("high"));
  it("REQ-EXC-06 creates stable deterministic explicit exception IDs", () => { const input = { rules: [rule("r1", "Use adapter except tests.", ["e1"])] }; return expect(detectExceptions(input).exceptions[0].id).toBe(detectExceptions(input).exceptions[0].id); });
  it("REQ-EXC-07 infers a webhook exception from two consistent outliers", () => expect(detectExceptions(inferredInput([{ fileId: "file-out", ruleId: "out", relativePath: "special/out.ts", description: "webhook", evidenceIds: ["eo"] }, { fileId: "file-out-2", ruleId: "out", relativePath: "special/out-2.ts", description: "webhook", evidenceIds: ["eo2"] }])).exceptions.some(e => e.kind === "inferred")).toBe(true));
  it("REQ-EXC-08 infers an external-integrations exception from consistent outliers", () => { const x = detectExceptions(inferredInput([{ fileId: "file-out", ruleId: "out", relativePath: "special/out.ts", description: "external-integrations", evidenceIds: ["eo"] }, { fileId: "file-out-2", ruleId: "out", relativePath: "special/out-2.ts", description: "external-integrations", evidenceIds: ["eo2"] }])); return expect(x.exceptions.some(e => e.description.includes("external-integrations"))).toBe(true); });
  it("REQ-EXC-09 refuses to infer an exception from one outlier", () => expect(detectExceptions(inferredInput([{ fileId: "file-out", ruleId: "out", relativePath: "special/out.ts", evidenceIds: ["eo"] }])).exceptions).toEqual([]));
  it("REQ-EXC-10 leaves unsupported outliers unexplained", () => expect(detectExceptions({ rules: [], outliers: [{ relativePath: "x.ts", description: "odd" }] }).unexplainedOutliers[0].description).toBe("odd"));
  it("REQ-EXC-11 lets an explicit named exception override an inferred duplicate", () => expect(detectExceptions({ ...inferredInput(), rules: [...inferredInput().rules, rule("explicit", "Use adapter except special/out.ts.", ["ex"])] }).exceptions.filter(e => e.description.includes("special/out.ts"))).toHaveLength(1));
  it("REQ-EXC-12 assigns medium confidence to two inferred paths", () => expect((detectExceptions(inferredInput()).exceptions.find(e => e.kind === "inferred") as any).confidence).toBe("medium"));
  it("REQ-EXC-13 assigns high confidence to three inferred paths", () => expect((detectExceptions({ ...inferredInput(), outliers: [{ fileId: "file-out", ruleId: "out", relativePath: "special/a.ts", evidenceIds: ["eoa"] }, { fileId: "file-out", ruleId: "out", relativePath: "special/b.ts", evidenceIds: ["eob"] }, { fileId: "file-out", ruleId: "out", relativePath: "special/c.ts", evidenceIds: ["eoc"] }] }).exceptions.find(e => e.kind === "inferred") as any).confidence).toBe("high"));
  it("REQ-EXC-14 preserves related convention IDs", () => expect((detectExceptions({ ...inferredInput(), conventions: [{ id: "conv-1", kind: "existing-utility-reuse", statement: "x", evidenceIds: ["e1", "e2"], affectedRelativePaths: [], explanation: "x" }] }).exceptions[0] as any).relatedConventionIds).toEqual(["conv-1"]));
  it("REQ-EXC-15 filters supporting fact IDs to inferred outlier paths", () => expect((detectExceptions({ ...inferredInput(), inventory: { ...inventory, facts: [{ id: "fact-in", kind: "import", relativePath: "special/out.ts", startLine: 1, endLine: 1, subject: "x", value: "x", excerpt: "x", excerptHash: "a".repeat(64) }, { id: "fact-out", kind: "import", relativePath: "src/other.ts", startLine: 1, endLine: 1, subject: "x", value: "x", excerpt: "x", excerptHash: "b".repeat(64) }] } }).exceptions[0] as any).supportingFactIds).toEqual(["fact-in"]));
  it("REQ-EXC-16 merges duplicate explicit exceptions deterministically", () => expect(detectExceptions({ rules: [rule("a", "Use adapter except tests.", ["e1"]), rule("b", "Use adapter except tests.", ["e2"])] }).exceptions).toHaveLength(1));
  it("REQ-EXC-17 rejects unsafe explicit exception paths", () => expect(detectExceptions({ rules: [rule("r", "Use adapter except ../../secret.", ["e"])] }).exceptions).toEqual([]));
  it("REQ-EXC-18 returns deterministically sorted exceptions and outliers", () => expect(detectExceptions({ rules: [rule("z", "Except z.", ["e2"]), rule("a", "Except a.", ["e1"])], outliers: [{ id: "z" }, { id: "a" }] }).exceptions.map(e => e.id)).toEqual([...detectExceptions({ rules: [rule("z", "Except z.", ["e2"]), rule("a", "Except a.", ["e1"])], outliers: [{ id: "z" }, { id: "a" }] }).exceptions].map(e => e.id))); 
  it("REQ-EXC-19 does not mutate rules conventions or inventory", () => { const input = { rules: [rule("r", "Except x.", ["e"])], conventions: [], inventory }; const before = structuredClone(input); detectExceptions(input); return expect(input).toEqual(before); });
  it("REQ-EXC-20 returns empty results for empty input", () => expect(detectExceptions({ rules: [] })).toEqual({ exceptions: [], findings: [], unexplainedOutliers: [] }));
});
