import { describe, expect, it } from "vitest";
import { validateEvidenceGraph, type EvidenceGraph } from "../src/intelligence/model.js";

const hash = "a".repeat(64);
const graph = (): EvidenceGraph => ({ metadata: { schemaVersion: "1.0", repositoryName: "repo", repositoryCommit: "commit", task: "task" }, sources: [{ id: "source-1", sourceType: "code", relativePath: "src/a.ts", sha256: hash, authority: "high" }], evidence: [{ id: "evidence-1", sourceId: "source-1", startLine: 1, endLine: 1, excerpt: "const a = 1", excerptHash: hash }], segments: [], rules: [{ id: "rule-1", statement: "Use a", normalizedSubject: "a", normalizedAction: "use", polarity: "require", scope: { include: [], exclude: [], technologies: [], taskKeywords: [] }, evidenceIds: ["evidence-1"] }], findings: [{ id: "finding-1", kind: "convention", summary: "A", evidenceIds: ["evidence-1"], affectedRuleIds: ["rule-1"], severity: "info", status: "open", explanation: "A" }], recommendations: [{ id: "recommendation-1", statement: "Use a", applicability: { include: [], exclude: [], technologies: [], taskKeywords: [] }, confidence: { level: "high", score: 100, reasons: ["direct evidence"], penalties: [] }, evidenceIds: ["evidence-1"], supportingFindingIds: ["finding-1"], contradictingFindingIds: [], exceptions: [], explanation: "Because" }] });
it("accepts minimal valid graph", () => expect(validateEvidenceGraph(graph()).valid).toBe(true));
it("rejects wrong schema version", () => { const value = graph(); value.metadata.schemaVersion = "2.0" as "1.0"; expect(validateEvidenceGraph(value).valid).toBe(false); });
it("rejects duplicate entity IDs across collections", () => { const value = graph(); value.segments.push({ id: "source-1", sourceId: "source-1", kind: "heading", startLine: 1, endLine: 1, rawExcerpt: "x", normalizedText: "x", excerptHash: hash }); expect(validateEvidenceGraph(value).errors.join()).toContain("duplicate ID"); });
it("rejects invalid hashes and spans", () => { const value = graph(); value.sources[0].sha256 = "BAD"; value.evidence[0].excerptHash = "BAD"; value.evidence[0].startLine = 0; value.evidence[0].endLine = 0; const errors = validateEvidenceGraph(value).errors.join(" "); expect(errors).toContain("SHA-256"); expect(errors).toContain("line range"); });
it("rejects missing source, evidence, rule, and finding references", () => { const value = graph(); value.evidence[0].sourceId = "no-source"; value.rules[0].evidenceIds = ["no-evidence"]; value.findings[0].affectedRuleIds = ["no-rule"]; value.recommendations[0].supportingFindingIds = ["no-finding"]; const errors = validateEvidenceGraph(value).errors.join(" "); expect(errors).toContain("missing source"); expect(errors).toContain("missing evidence"); expect(errors).toContain("missing rule"); expect(errors).toContain("missing findings"); });
it("rejects zero evidence recommendations", () => { const value = graph(); value.recommendations[0].evidenceIds = []; expect(validateEvidenceGraph(value).valid).toBe(false); });
it("rejects confidence below, above, decimal, and without reasons", () => { for (const score of [-1, 101, 1.5]) { const value = graph(); value.recommendations[0].confidence.score = score; expect(validateEvidenceGraph(value).valid).toBe(false); } const value = graph(); value.recommendations[0].confidence.reasons = ["", "  "]; expect(validateEvidenceGraph(value).valid).toBe(false); });
it("rejects duplicate reference IDs", () => { const value = graph(); value.rules[0].evidenceIds = ["evidence-1", "evidence-1"]; expect(validateEvidenceGraph(value).errors.join()).toContain("duplicate reference ID"); });
it("rejects malformed roots and reports multiple sorted errors without mutation", () => { expect(validateEvidenceGraph(null).valid).toBe(false); const value = graph(); value.metadata.schemaVersion = "0.1" as "1.0"; value.evidence[0].sourceId = "missing"; const before = JSON.stringify(value); const result = validateEvidenceGraph(value); expect(result.errors.length).toBeGreaterThan(1); expect(result.errors).toEqual([...result.errors].sort((a, b) => a.localeCompare(b))); expect(JSON.stringify(value)).toBe(before); });
