import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it } from "vitest";
import { compileRepositoryIntelligence } from "../src/intelligence/compile-repository-intelligence.js";

const roots: string[] = [];
afterEach(async () => { await Promise.all(roots.splice(0).map(p => rm(p, { recursive: true, force: true }))); });
const fixture = async (files: Record<string, string> = {}): Promise<string> => { const root = await mkdtemp(join(tmpdir(), "camarade-c-")); roots.push(root); for (const [name, content] of Object.entries(files)) { const target = join(root, name); await writeFile(target, content); } return root; };

describe("repository intelligence compiler", () => {
  it("produces deterministic artifacts", async () => { const root = await fixture({ "AGENTS.md": "- Always use the existing utility.\n" }); const a = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect utilities" }); const b = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect utilities" }); expect(a.artifact.id).toBe(b.artifact.id); expect(a.artifact.summary.ruleCount).toBe(1); });
  it("REQ-COMP-01 rejects an empty repository path", async () => { await expect(compileRepositoryIntelligence({ repositoryPath: "", task: "inspect" })).rejects.toThrow(); });
  it("REQ-COMP-02 rejects an empty task and empty explicit repository ID", async () => { const root = await fixture(); await expect(compileRepositoryIntelligence({ repositoryPath: root, task: "" })).rejects.toThrow(); await expect(compileRepositoryIntelligence({ repositoryPath: root, task: "inspect", repositoryId: "" })).rejects.toThrow(); });
  it("REQ-COMP-03 resolves repository ID using the required precedence", async () => { const root = await fixture({ "package.json": "{\"name\":\"package-name\"}\n" }); expect((await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect", repositoryId: "explicit-id" })).artifact.repositoryId).toBe("explicit-id"); expect((await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect" })).artifact.repositoryId).toBe("package-name"); });
  it("REQ-COMP-04 discovers only supported instruction and architecture sources", async () => { const root = await fixture({ "AGENTS.md": "- Use the utility.\n", "README.md": "Architecture overview.\n", "notes.txt": "ignore\n" }); const result = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect" }); expect(result.sources.map(s => s.relativePath).sort()).toEqual(["AGENTS.md", "README.md"]); expect(result.artifact.architectureDecisions).toBeDefined(); });
  it("REQ-COMP-05 uses the existing segmentation parsing and scope pipeline", async () => { const root = await fixture({ "AGENTS.md": "## Scope\n- Always use the existing utility.\n" }); const result = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect utilities" }); expect(result.artifact.rules.length).toBeGreaterThan(0); expect(result.artifact.evidenceIndex.length).toBeGreaterThan(0); });
  it("REQ-COMP-06 executes reference duplicate and contradiction detection", async () => { const root = await fixture({ "AGENTS.md": "- Always use utility A.\n- Never use utility A.\n" }); const result = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect" }); expect(result.artifact.findings).toBeDefined(); expect(result.artifact.references).toBeDefined(); });
  it("REQ-COMP-07 mines conventions architecture decisions and exceptions", async () => { const root = await fixture({ "AGENTS.md": "- Use existing utility.\n" }); const result = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect" }); expect(result.artifact.conventions).toBeDefined(); expect(result.artifact.architectureDecisions).toBeDefined(); expect(result.artifact.exceptions).toBeDefined(); });
  it("REQ-COMP-08 scores every finding and generates one recommendation per finding", async () => { const root = await fixture({ "AGENTS.md": "- Always use utility A.\n- Never use utility A.\n" }); const result = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect" }); expect(result.artifact.confidenceAssessments).toHaveLength(result.artifact.findings.length); expect(result.artifact.recommendations).toHaveLength(result.artifact.findings.length); });
  it("REQ-COMP-09 builds the actual node-edge graph artifact and canonical JSON", async () => { const root = await fixture({ "AGENTS.md": "- Use utility.\n" }); const result = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect" }); expect(result.artifact.graph.nodes).toBeInstanceOf(Array); expect(result.artifact.graph.edges).toBeInstanceOf(Array); expect(result.artifact.graph.danglingReferences).toBeInstanceOf(Array); expect(result.artifact.graph).not.toHaveProperty("metadata"); expect(JSON.parse(result.artifactJson).id).toBe(result.artifact.id); expect(result.artifactJson.endsWith("\n")).toBe(true); });
  it("REQ-COMP-10 disables Git history deterministically when requested", async () => { const root = await fixture(); const a = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect", includeGitHistory: false }); const b = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect", includeGitHistory: false }); expect(a.artifact.history.availability).toBe("unavailable"); expect(a.artifactJson).toBe(b.artifactJson); expect((a.artifact.history as typeof a.artifact.history & { unavailableReason?: string }).unavailableReason).toBe("Git-history analysis disabled."); });
  it("REQ-COMP-11 continues with unavailable Git history for a non-Git repository", async () => { const root = await mkdtemp(join(tmpdir(), "camarade-nongit-")); roots.push(root); const result = await compileRepositoryIntelligence({ repositoryPath: root, task: "inspect" }); expect(result.artifact.history.availability).toBe("unavailable"); expect((result.artifact.history as typeof result.artifact.history & { unavailableReason?: string }).unavailableReason).toBe("Git-history analysis unavailable: repository is not a Git repository."); });
  it("REQ-COMP-12 returns stable output without mutating options", async () => { const root = await fixture({ "AGENTS.md": "- Use utility.\n" }); const options = { repositoryPath: root, task: "inspect", includeGitHistory: false }; const before = structuredClone(options); const a = await compileRepositoryIntelligence(options); const b = await compileRepositoryIntelligence(options); expect(options).toEqual(before); expect(a.artifactJson).toBe(b.artifactJson); });
});
