import { describe, expect, it } from "vitest";
import { evaluateIntelligenceArtifact } from "../src/intelligence/evaluate-intelligence-artifact.js";

describe("intelligence artifact evaluator", () => {
  it("REQ-EVAL-01 fails for an open error finding", () => { const result = evaluateIntelligenceArtifact({ schemaVersion: "1.0.0", findings: [{ id: "error-1", status: "open", severity: "error" }] }); expect(result.status).toBe("fail"); expect(result.exitCode).toBe(1); expect(result.openErrorFindingIds).toEqual(["error-1"]); });
  it("REQ-EVAL-02 fails for a critical recommendation", () => { const result = evaluateIntelligenceArtifact({ schemaVersion: "1.0.0", recommendations: [{ id: "critical-1", priority: "critical" }] }); expect(result.status).toBe("fail"); expect(result.criticalRecommendationIds).toEqual(["critical-1"]); });
  it("REQ-EVAL-03 fails for graph dangling references", () => { const result = evaluateIntelligenceArtifact({ schemaVersion: "1.0.0", graph: { sources: [], evidence: [{ id: "e1", sourceId: "missing" }] } }); expect(result.status).toBe("fail"); expect(result.danglingReferenceCount).toBe(1); });
  it("REQ-EVAL-04 warns for open warning findings high recommendations or outliers", () => { const result = evaluateIntelligenceArtifact({ schemaVersion: "1.0.0", findings: [{ id: "warning-1", status: "open", severity: "warning" }], recommendations: [{ id: "high-1", priority: "high" }], unexplainedOutlierPaths: ["src/outlier.ts"] }); expect(result.status).toBe("warn"); expect(result.exitCode).toBe(2); expect(result.openWarningFindingIds).toEqual(["warning-1"]); expect(result.highRecommendationIds).toEqual(["high-1"]); expect(result.unexplainedOutlierCount).toBe(1); });
  it("REQ-EVAL-05 passes a clean artifact", () => { const result = evaluateIntelligenceArtifact({ schemaVersion: "1.0.0" }); expect(result).toMatchObject({ status: "pass", exitCode: 0, danglingReferenceCount: 0, unexplainedOutlierCount: 0 }); });
  it("REQ-EVAL-06 applies fail precedence over warning conditions", () => { const result = evaluateIntelligenceArtifact({ schemaVersion: "1.0.0", findings: [{ id: "warning-1", status: "open", severity: "warning" }, { id: "error-1", status: "open", severity: "error" }], recommendations: [{ id: "high-1", priority: "high" }] }); expect(result.status).toBe("fail"); expect(result.exitCode).toBe(1); });
  it("REQ-EVAL-07 rejects an unsupported artifact schema version", () => { const result = evaluateIntelligenceArtifact({ schemaVersion: "2.0.0" }); expect(result.status).toBe("fail"); expect(result.errors).toContain("schemaVersion: unsupported artifact schema version"); });
  it("REQ-EVAL-08 returns deterministic sorted IDs without mutating the artifact", () => { const artifact = { schemaVersion: "1.0.0", findings: [{ id: "z", status: "open", severity: "error" }, { id: "a", status: "open", severity: "error" }, { id: "z", status: "open", severity: "error" }] }; const before = structuredClone(artifact); const result = evaluateIntelligenceArtifact(artifact); expect(result.openErrorFindingIds).toEqual(["a", "z"]); expect(artifact).toEqual(before); expect(result).toEqual(evaluateIntelligenceArtifact(before)); });
});
