import { describe, expect, it } from "vitest";
import { evaluateIntelligenceArtifact } from "../src/intelligence/evaluate-intelligence-artifact.js";

const graph = () => ({ id: "graph_empty", nodes: [], edges: [], danglingReferences: [] });
const artifact = (overrides: Record<string, unknown> = {}) => ({ schemaVersion: "1.0.0", graph: graph(), ...overrides });

describe("intelligence artifact evaluator", () => {
  it("REQ-EVAL-01 fails for an open error finding", () => { const result = evaluateIntelligenceArtifact(artifact({ findings: [{ id: "error-1", status: "open", severity: "error" }] })); expect(result.status).toBe("fail"); expect(result.exitCode).toBe(1); expect(result.openErrorFindingIds).toEqual(["error-1"]); });
  it("REQ-EVAL-02 fails for a critical recommendation", () => { const result = evaluateIntelligenceArtifact(artifact({ recommendations: [{ id: "critical-1", priority: "critical" }] })); expect(result.status).toBe("fail"); expect(result.criticalRecommendationIds).toEqual(["critical-1"]); });
  it("REQ-EVAL-03 fails for graph dangling references", () => { const result = evaluateIntelligenceArtifact(artifact({ graph: { id: "graph_dangling", nodes: [{ id: "e1", kind: "evidence", label: "e1" }], edges: [], danglingReferences: [{ ownerId: "e1", relation: "sourceId", missingId: "missing" }] } })); expect(result.status).toBe("fail"); expect(result.valid).toBe(false); expect(result.danglingReferenceCount).toBe(1); });
  it("REQ-EVAL-04 warns for open warning findings high recommendations or outliers", () => { const result = evaluateIntelligenceArtifact(artifact({ findings: [{ id: "warning-1", status: "open", severity: "warning" }], recommendations: [{ id: "high-1", priority: "high" }], unexplainedOutlierPaths: ["src/outlier.ts"] })); expect(result.status).toBe("warn"); expect(result.exitCode).toBe(2); expect(result.openWarningFindingIds).toEqual(["warning-1"]); expect(result.highRecommendationIds).toEqual(["high-1"]); expect(result.unexplainedOutlierCount).toBe(1); });
  it("REQ-EVAL-05 passes a clean artifact", () => { const result = evaluateIntelligenceArtifact(artifact()); expect(result).toMatchObject({ status: "pass", exitCode: 0, valid: true, danglingReferenceCount: 0, unexplainedOutlierCount: 0 }); });
  it("REQ-EVAL-06 applies fail precedence over warning conditions", () => { const result = evaluateIntelligenceArtifact(artifact({ findings: [{ id: "warning-1", status: "open", severity: "warning" }, { id: "error-1", status: "open", severity: "error" }], recommendations: [{ id: "high-1", priority: "high" }] })); expect(result.status).toBe("fail"); expect(result.exitCode).toBe(1); });
  it("REQ-EVAL-07 rejects an unsupported artifact schema version", () => { const result = evaluateIntelligenceArtifact(artifact({ schemaVersion: "2.0.0" })); expect(result.status).toBe("fail"); expect(result.valid).toBe(false); expect(result.errors).toContain("UNSUPPORTED_ARTIFACT_VERSION: schemaVersion is unsupported"); });
  it("REQ-EVAL-08 returns deterministic sorted IDs without mutating the artifact", () => { const value = artifact({ findings: [{ id: "z", status: "open", severity: "error" }, { id: "a", status: "open", severity: "error" }, { id: "z", status: "open", severity: "error" }] }); const before = structuredClone(value); const result = evaluateIntelligenceArtifact(value); expect(result.openErrorFindingIds).toEqual(["a", "z"]); expect(value).toEqual(before); expect(result).toEqual(evaluateIntelligenceArtifact(before)); });
  it("REQ-EVAL-09 rejects malformed actual graph endpoints", () => { const result=evaluateIntelligenceArtifact(artifact({ graph: { id: "graph_broken", nodes: [{ id: "node_a", kind: "source", label: "a" }], edges: [{ id: "edge_a", kind: "contains", fromId: "node_a", toId: "missing", explanation: "broken" }], danglingReferences: [] } })); expect(result.status).toBe("fail"); expect(result.valid).toBe(false); expect(result.errors.join("\n")).toContain("graph.edges[0].toId: missing node reference 'missing'"); });
  it("REQ-EVAL-10 requires the actual graph on schema 1.0.0 artifacts", () => { const result=evaluateIntelligenceArtifact({ schemaVersion: "1.0.0" }); expect(result.status).toBe("fail"); expect(result.valid).toBe(false); expect(result.errors).toContain("graph.root: expected an object"); });
  it("REQ-EVAL-11 keeps open conflicts structurally valid for Stage 4", () => { const result=evaluateIntelligenceArtifact(artifact({ findings: [{ id: "conflict-1", kind: "contradiction", status: "open", severity: "error" }], recommendations: [{ id: "resolve-1", priority: "critical" }] })); expect(result.status).toBe("fail"); expect(result.exitCode).toBe(1); expect(result.valid).toBe(true); });
});
