import { createHash } from "node:crypto";
import { promises as fs } from "node:fs";
import os from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { inventoryRepository, MAX_INVENTORY_FILE_BYTES, rankRelevantFiles } from "../src/intelligence/inventory-repository.js";

describe("repository inventory coverage", () => {
  it("covers safe deterministic inventory and ranking", async () => {
    const root = await fs.mkdtemp(path.join(os.tmpdir(), "camarade-inventory-"));
    try {
      await expect(inventoryRepository("")).rejects.toThrow("empty");
      await expect(inventoryRepository(path.join(root, "missing"))).rejects.toThrow("does not exist");
      const plain = path.join(root, "plain"); await fs.writeFile(plain, "x"); await expect(inventoryRepository(plain)).rejects.toThrow("not a directory"); await fs.unlink(plain);
      await fs.mkdir(path.join(root, "src", "nested"), { recursive: true });
      for (const d of [".git", "node_modules", "dist", "coverage", ".camarade"]) await fs.mkdir(path.join(root, d));
      await fs.writeFile(path.join(root, "AGENTS.md"), "Always use TypeScript.\n"); await fs.mkdir(path.join(root, ".cursor", "rules"), { recursive: true }); await fs.writeFile(path.join(root, ".cursor/rules/r.md"), "Must use tests."); await fs.mkdir(path.join(root, ".github"), { recursive: true }); await fs.writeFile(path.join(root, ".github/copilot-instructions.md"), "Use CI.");
      await fs.mkdir(path.join(root, "docs")); await fs.writeFile(path.join(root, "docs/readme.md"), "docs"); await fs.writeFile(path.join(root, "config.yaml"), "x: y"); await fs.writeFile(path.join(root, "data.yml"), "x: y"); await fs.writeFile(path.join(root, "data.json"), "{}"); await fs.writeFile(path.join(root, "notes.mdx"), "notes"); await fs.writeFile(path.join(root, "script.js"), "export const x = 1;"); await fs.writeFile(path.join(root, "script.jsx"), "export const x = 1;"); await fs.writeFile(path.join(root, "script.mjs"), "export const x = 1;"); await fs.writeFile(path.join(root, "script.cjs"), "module.exports = {};"); await fs.writeFile(path.join(root, "package.json"), JSON.stringify({ scripts: { test: "vitest" }, dependencies: { react: "1" }, devDependencies: { vitest: "1" } }));
      const code = '"use server";\nimport { middlewareThing } from "./middleware";\nexport { x } from "./other";\nconst x = require("./x");\nimport("./lazy"); import(foo);\nexport function GET() { return x; }\nexport const value = 1;\nfunction action() { "use server"; }\n'; await fs.writeFile(path.join(root, "src/nested/app.ts"), code); await fs.writeFile(path.join(root, "src/nested/app.test.ts"), "export const testValue = 1;"); await fs.writeFile(path.join(root, "blob.bin"), Buffer.from([1, 0, 2])); await fs.writeFile(path.join(root, "huge.txt"), Buffer.alloc(MAX_INVENTORY_FILE_BYTES + 1, 65));
      let symlinkCreated = true; try { await fs.symlink("/tmp", path.join(root, "outside-link")); } catch { symlinkCreated = false; }
      const first = await inventoryRepository(root), second = await inventoryRepository(root);
      expect(first.files.map(f => f.relativePath)).toEqual([...first.files.map(f => f.relativePath)].sort()); expect(first.directories).toEqual([...first.directories].sort()); expect(first.files.every(f => !path.isAbsolute(f.relativePath) && !f.relativePath.includes("\\"))).toBe(true); expect(first.directories).not.toContain(""); expect(JSON.stringify(first)).not.toContain(root); expect(first.files.map(f => f.relativePath)).not.toContain(".git/x");
      const app = first.files.find(f => f.relativePath.endsWith("app.ts"))!; expect(app.kind).toBe("source"); expect(app.language).toBe("typescript"); expect(app.sizeBytes).toBe(Buffer.byteLength(code)); expect(app.sha256).toBe(createHash("sha256").update(code).digest("hex")); expect(first.facts.some(f => f.kind === "file-exists" && f.relativePath === app.relativePath)).toBe(true); expect(first.files.find(f => f.relativePath === "script.js")?.language).toBe("javascript"); expect(first.files.find(f => f.relativePath === "script.jsx")?.language).toBe("javascript"); expect(first.files.find(f => f.relativePath === "script.mjs")?.language).toBe("javascript"); expect(first.files.find(f => f.relativePath === "script.cjs")?.language).toBe("javascript"); expect(first.files.find(f => f.relativePath === "data.json")?.language).toBe("json"); expect(first.files.find(f => f.relativePath === "config.yaml")?.language).toBe("yaml"); expect(first.files.find(f => f.relativePath === "data.yml")?.language).toBe("yaml"); expect(first.files.find(f => f.relativePath === "notes.mdx")?.language).toBe("markdown");
      expect(first.files.find(f => f.relativePath === "AGENTS.md")?.kind).toBe("instruction"); expect(first.files.find(f => f.relativePath === "docs/readme.md")?.kind).toBe("documentation"); expect(first.files.find(f => f.relativePath === "package.json")?.kind).toBe("configuration"); expect(first.files.find(f => f.relativePath.endsWith("app.test.ts"))?.kind).toBe("test");
      for (const [kind, value] of [["package-script", "scripts.test"], ["dependency", "react"], ["dev-dependency", "vitest"], ["framework", "react"], ["test-framework", "vitest"]] as const) expect(first.facts.some(f => f.kind === kind && f.subject === value)).toBe(true);
      for (const value of ["./middleware", "./other", "./x", "./lazy"]) expect(first.facts.some(f => f.kind === "import" && f.value === value)).toBe(true); expect(first.facts.some(f => f.kind === "middleware-reference" && f.value === "./middleware")).toBe(true); expect(first.facts.some(f => f.kind === "middleware-reference" && f.subject === "middlewareThing")).toBe(true); expect(first.facts.some(f => f.kind === "export" && f.subject === "GET")).toBe(true); expect(first.facts.some(f => f.kind === "server-action" && f.value === "module")).toBe(true); expect(first.facts.some(f => f.kind === "server-action" && f.value === "function")).toBe(true); expect(first.facts.some(f => f.kind === "route-handler" && f.subject === "GET")).toBe(true); expect(first.facts.filter(f => f.relativePath.endsWith("app.ts") && f.kind === "import").every(f => f.startLine >= 2 && f.endLine <= 5)).toBe(true); expect(first.facts.some(f => f.value === "foo")).toBe(false);
      expect(first.skipped.some(s => s.relativePath === "blob.bin" && s.reason === "Binary file content is not analyzed.")).toBe(true); expect(first.skipped.some(s => s.relativePath === "huge.txt" && s.reason === "File exceeds inventory size limit.")).toBe(true); expect(first.skipped.some(s => s.reason === "Symbolic links are not followed.")).toBe(symlinkCreated); expect(first.files.map(f => f.id)).toEqual(second.files.map(f => f.id));
      const otherRoot = await fs.mkdtemp(path.join(os.tmpdir(), "camarade-inventory-other-")); try { await fs.mkdir(path.join(otherRoot, "src/nested"), { recursive: true }); await fs.writeFile(path.join(otherRoot, "src/nested/app.ts"), code); const other = await inventoryRepository(otherRoot); expect(other.files.find(f => f.relativePath === "src/nested/app.ts")?.id).toBe(app.id); } finally { await fs.rm(otherRoot, { recursive: true, force: true }); }
      const invalidRoot = await fs.mkdtemp(path.join(os.tmpdir(), "camarade-inventory-invalid-")); try { await fs.writeFile(path.join(invalidRoot, "package.json"), "{"); const invalid = await inventoryRepository(invalidRoot); expect(invalid.skipped.some(s => s.relativePath === "package.json")).toBe(true); } finally { await fs.rm(invalidRoot, { recursive: true, force: true }); }
      const original = structuredClone(first); const rules = [{ statement: "src/nested/app.ts", scope: { include: ["src/nested/app.ts"], exclude: [], technologies: [], taskKeywords: [] } }] as never[]; const ranked = rankRelevantFiles(first, "app middleware", rules); expect(ranked[0].score).toBeGreaterThan(0); expect(ranked.some(f => f.relativePath.endsWith("app.test.ts"))).toBe(true); expect(ranked.every(f => f.score <= 100)).toBe(true); expect(ranked.some(f => f.score === 0)).toBe(false); expect(rankRelevantFiles(first, "")).toEqual([]); expect(first).toEqual(original); expect(rules).toEqual(rules);
    } finally { await fs.rm(root, { recursive: true, force: true }); }
  });

  it("REQ-INV-06 ignores required directories at every depth", async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), "inv-06-")); try { for (const d of [".git", "node_modules", "dist", "coverage", ".camarade"]) { await fs.mkdir(path.join(root, "a", d), { recursive: true }); await fs.writeFile(path.join(root, "a", d, "hidden.txt"), "x"); } const inventory = await inventoryRepository(root); expect(inventory.files.some(f => f.relativePath.includes("hidden.txt"))).toBe(false); } finally { await fs.rm(root, { recursive: true, force: true }); } });
  it("REQ-INV-07 records symbolic links as skipped", async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), "inv-07-")); try { await fs.writeFile(path.join(root, "target.txt"), "x"); await fs.symlink("target.txt", path.join(root, "link.txt")); const inventory = await inventoryRepository(root); expect(inventory.skipped).toContainEqual({ relativePath: "link.txt", reason: "Symbolic links are not followed." }); } finally { await fs.rm(root, { recursive: true, force: true }); } });
  it("REQ-INV-08 never follows a symbolic link outside the repository", async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), "inv-08-")); const outside = await fs.mkdtemp(path.join(os.tmpdir(), "inv-08-out-")); try { await fs.writeFile(path.join(outside, "secret.txt"), "secret"); await fs.symlink(outside, path.join(root, "external")); const inventory = await inventoryRepository(root); expect(inventory.files.some(f => f.relativePath.includes("secret.txt"))).toBe(false); } finally { await fs.rm(root, { recursive: true, force: true }); await fs.rm(outside, { recursive: true, force: true }); } });
  it("REQ-INV-36 records exact one-based fact line ranges", async () => { const root = await fs.mkdtemp(path.join(os.tmpdir(), "inv-36-")); try { await fs.writeFile(path.join(root, "app.ts"), "const a = 1;\nexport function GET() {\n  return a;\n}\n"); const inventory = await inventoryRepository(root); const route = inventory.facts.find(f => f.kind === "route-handler"); expect(route).toMatchObject({ startLine: 2, endLine: 4 }); } finally { await fs.rm(root, { recursive: true, force: true }); } });
  it("REQ-INV-42 awards exact path-match ranking points", () => { const file = { id: "f", relativePath: "src/auth/login.ts", kind: "source" as const, language: "typescript" as const, sizeBytes: 1, sha256: "a".repeat(64) }; const result = rankRelevantFiles({ directories: [], files: [file], facts: [], skipped: [] }, "auth login"); expect(result[0].score).toBe(50); });
  it("REQ-INV-43 awards exact fact-match ranking points", () => { const file = { id: "f", relativePath: "src/file.ts", kind: "source" as const, language: "typescript" as const, sizeBytes: 1, sha256: "a".repeat(64) }; const fact = { id: "fact_1", kind: "export" as const, relativePath: "src/file.ts", startLine: 1, endLine: 1, subject: "authentication", value: "login", excerpt: "login", excerptHash: "b".repeat(64) }; const result = rankRelevantFiles({ directories: [], files: [file], facts: [fact], skipped: [] }, "authentication login"); expect(result[0].score).toBe(20); });
  it("REQ-INV-44 awards the exact rule statement path bonus", () => { const file = { id: "f", relativePath: "src/file.ts", kind: "source" as const, language: "typescript" as const, sizeBytes: 1, sha256: "a".repeat(64) }; const rule = { statement: "Edit src/file.ts", scope: { include: ["**/*"], exclude: [], technologies: [], taskKeywords: [] } } as never; expect(rankRelevantFiles({ directories: [], files: [file], facts: [], skipped: [] }, "edit", [rule])[0].score).toBe(20); });
  it("REQ-INV-45 awards the exact rule scope include path bonus", () => { const file = { id: "f", relativePath: "src/file.ts", kind: "source" as const, language: "typescript" as const, sizeBytes: 1, sha256: "a".repeat(64) }; const rule = { statement: "Keep code stable", scope: { include: ["src/file.ts"], exclude: [], technologies: [], taskKeywords: [] } } as never; expect(rankRelevantFiles({ directories: [], files: [file], facts: [], skipped: [] }, "stable", [rule])[0].score).toBe(20); });
  it("REQ-INV-46 awards the test counterpart bonus exactly once", () => { const source = { id: "s", relativePath: "src/login.ts", kind: "source" as const, language: "typescript" as const, sizeBytes: 1, sha256: "a".repeat(64) }; const test = { id: "t", relativePath: "src/login.test.ts", kind: "test" as const, language: "typescript" as const, sizeBytes: 1, sha256: "b".repeat(64) }; const result = rankRelevantFiles({ directories: [], files: [source, test], facts: [], skipped: [] }, "login"); expect(result.find(f => f.relativePath === "src/login.test.ts")?.score).toBe(40); });
  it("REQ-INV-49 sorts candidates by score then relative path", () => { const files = ["z.ts", "a.ts"].map((relativePath, i) => ({ id: String(i), relativePath, kind: "source" as const, language: "typescript" as const, sizeBytes: 1, sha256: String(i).repeat(64) })); const facts = files.map((file, i) => ({ id: `fact_${i}`, kind: "export" as const, relativePath: file.relativePath, startLine: 1, endLine: 1, subject: "common", value: "value", excerpt: "value", excerptHash: String(i).repeat(64) })); const result = rankRelevantFiles({ directories: [], files, facts, skipped: [] }, "common"); expect(result.map(f => f.relativePath)).toEqual(["a.ts", "z.ts"]); });
  it("REQ-INV-50 does not mutate inventory or rules", () => { const file = { id: "f", relativePath: "src/file.ts", kind: "source" as const, language: "typescript" as const, sizeBytes: 1, sha256: "a".repeat(64) }; const inventory = { directories: [], files: [file], facts: [], skipped: [] }; const rules = [{ statement: "Edit src/file.ts", scope: { include: ["src/file.ts"], exclude: [], technologies: [], taskKeywords: [] } }] as never[]; const beforeInventory = structuredClone(inventory), beforeRules = structuredClone(rules); rankRelevantFiles(inventory, "edit", rules); expect(inventory).toEqual(beforeInventory); expect(rules).toEqual(beforeRules); });
});
