import { lstat, mkdir, readFile, rename, symlink, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { describe, expect, it, vi } from "vitest";
import { canonicalJson, sha256 } from "../src/context/context-serialization.js";
import { validateExplanationArtifacts, writeExplanationArtifacts } from "../src/explanation/explanation-artifacts.js";
import { buildImpactExplanation } from "../src/explanation/build-impact-explanation.js";
import { explainCompletedExperiment } from "../src/explanation/explain-completed-experiment.js";
import { mkdtemp } from "node:fs/promises";
import { tmpdir } from "node:os";

async function f(status: "valid" | "limited" | "invalid" = "valid") { const root = await mkdtemp(join(tmpdir(), "camarade-s7-tamper-")); const result = buildImpactExplanation({ instructions: [{ instructionId: "i-1", identity: "Keep validation", sourceRef: "rules.json" }], baseline: {}, optimized: { checkResults: [{ instructionId: "i-1", sourceRef: "check.json", status: "passed" }] }, experimentStatus: status }); await writeExplanationArtifacts(root, "cmp-1", status, result); return root; }
const clean = async (root: string) => { const { rm } = await import("node:fs/promises"); await rm(root, { recursive: true, force: true }); };

describe("S7-03 explanation tamper and status behavior", () => {
  it("service uses validated persisted condition evidence and disk readback", async () => { const controller = await mkdtemp(join(tmpdir(), "camarade-s7-service-")); const root = join(controller, ".camarade", "runs", "cmp-service"); await mkdir(root, { recursive: true }); const id = `instruction-${"a".repeat(16)}`; const stage4 = join(controller, ".camarade", "compilations", "cmp-service", "contract.json"); await mkdir(join(controller, ".camarade", "compilations", "cmp-service"), { recursive: true }); await writeFile(stage4, JSON.stringify({ records: [{ instructionId: id, dependency: "legacy-router", status: "removed", sourceRef: "stage-4/baseline.json" }, { instructionId: id, kind: "active-replacement", sourceRef: "stage-4/baseline.json" }], taskScope: { irrelevantInstructions: [{ instructionId: id }] } })); const persisted = { specification: { experimentId: "cmp-service", task: "persisted", taskScope: { irrelevantInstructions: [{ instructionId: id }] } }, manifest: { conditionContextManifests: [{ conditionId: "baseline", sources: [{ relativePath: "/private/internal/AGENTS.md", contentHash: "a".repeat(64) }], stage4ArtifactPaths: [stage4] }, { conditionId: "camarade", sources: [{ relativePath: "/private/internal/compiled.md", contentHash: "b".repeat(64) }] }] }, baseline: {}, camarade: {} }; const verify = vi.spyOn(await import("../src/evaluation/verify-experiment-integrity.js"), "verifyExperimentIntegrity").mockResolvedValue({ status: "valid", experimentId: "cmp-service", experimentDirectory: root, experiment: persisted } as any); const result = await explainCompletedExperiment({ experimentDirectory: root }); const impact = JSON.parse(await readFile(join(root, "explanation/instruction-impacts.json"), "utf8")); expect(verify).toHaveBeenCalledWith(root); expect(result.counts.total).toBeGreaterThan(0); expect(impact.records.some((record: any) => record.evidence.some((e: any) => e.sourceRef === "stage-4/baseline.json"))).toBe(true); expect(result.artifacts.directory).toBe("explanation"); expect(JSON.stringify(result)).not.toMatch(/\/private\/|\/Users\/|\/tmp\//); await clean(controller); verify.mockRestore(); });
  it("[R09] reject traversal", async () => { const root = await f(); const p = join(root, "explanation/evidence-index.json"); const x = JSON.parse(await readFile(p, "utf8")); x.entries[0].relativePath = "../escape"; await writeFile(p, canonicalJson(x)); await expect(validateExplanationArtifacts(root, "cmp-1")).rejects.toThrow(); await clean(root); });
  it("[R10] reject symlink escape", async () => { const root = await f(); const target = join(root, "outside"); await writeFile(target, "secret"); const path = join(root, "explanation/REPORT.md"); const saved = join(root, "report-real"); await rename(path, saved); await symlink(target, path); await expect(validateExplanationArtifacts(root, "cmp-1")).rejects.toThrow(); await clean(root); });
  it("[R11] reject tampered impact artifact", async () => { const root = await f(); const p = join(root, "explanation/instruction-impacts.json"); await writeFile(p, `${await readFile(p, "utf8")}x`); await expect(validateExplanationArtifacts(root, "cmp-1")).rejects.toThrow(); await clean(root); });
  it("[R12] reject tampered report", async () => { const root = await f(); const p = join(root, "explanation/REPORT.md"); await writeFile(p, `${await readFile(p, "utf8")}tampered`); await expect(validateExplanationArtifacts(root, "cmp-1")).rejects.toThrow(); await clean(root); });
  it("[R13] repeated explanation overwrite", async () => { const root = await f(); const before = await readFile(join(root, "explanation/evidence-index.json"), "utf8"); const result = buildImpactExplanation({ instructions: [{ instructionId: "i-1", identity: "Keep validation", sourceRef: "rules.json" }], baseline: {}, optimized: {} }); await expect(writeExplanationArtifacts(root, "cmp-1", "valid", result)).rejects.toThrow(/already exists/); expect(await readFile(join(root, "explanation/evidence-index.json"), "utf8")).toBe(before); await clean(root); });
  it("[R14] limited experiment behavior", async () => { const root = await f("limited"); const a = await validateExplanationArtifacts(root, "cmp-1"); expect(a.result.records.every(r => r.impact.direction !== "helped" && r.impact.direction !== "hurt")).toBe(true); expect((a.summary.limitations as string[]).length).toBeGreaterThan(0); await clean(root); });
  it("[R15] invalid experiment behavior", async () => { const root = await f("invalid"); const a = await validateExplanationArtifacts(root, "cmp-1"); expect(a.result.records.every(r => r.impact.direction !== "helped" && r.impact.direction !== "hurt")).toBe(true); expect(a.summary.evidenceStatus).toMatch(/invalid/i); await clean(root); });
  it("[R16] repeated clean runs equivalent excluding allowed IDs/timestamps", async () => { const a = await f(); const b = await f(); const ai = await validateExplanationArtifacts(a, "cmp-1"); const bi = await validateExplanationArtifacts(b, "cmp-1"); expect(ai.result).toEqual(bi.result); expect(ai.summary).toEqual(bi.summary); expect(ai.report).toBe(bi.report); expect(ai.index.aggregateHash).toBe(bi.index.aggregateHash); await clean(a); await clean(b); });
});
