import { describe,expect,it } from "vitest";
import { CATEGORY_WEIGHTS,scorePair,resolveOutcome,resolveStatus,resolveMaterialOverride } from "../src/evaluation/scoring.js";
function e(over:any={}, second?:any):any { const changes={expectedPaths:["a"],unnecessaryPaths:[],protectedPathViolations:[],missingRequiredChangedPaths:[],ignoredPaths:[],...(over.changes||{})}; return {...over,correctness:over.correctness??[{status:"pass",weight:1}],requirements:over.requirements??[{status:"pass",weight:1}],rules:over.rules??[{status:"pass",weight:1}],changes}; }
describe("S6-R2 scoring scenarios",()=>{
it("[S01] fixed weights",()=>{expect(CATEGORY_WEIGHTS).toMatchObject({correctness:40,requirementCompletion:25,instructionCompliance:20,changeFocus:10,efficiency:5,tokenEfficiency:3,runtimeEfficiency:2});});
it("[S02] correctness denominator",()=>{expect(scorePair(e({correctness:[{status:"pass",weight:2},{status:"fail",weight:8}]})).baseline.correctness.score).toBe(8);});
it("[S03] correctness measurable maximum",()=>{expect(scorePair(e({correctness:[{status:"pass",weight:2},{status:"unavailable",weight:8}]})).baseline.correctness.measurableMaximum).toBe(8);});
it("[S04] requirement denominator",()=>{expect(scorePair(e({requirements:[{status:"pass",weight:1},{status:"fail",weight:1}]})).baseline.requirementCompletion.score).toBe(12.5);});
it("[S05] requirement measurable maximum",()=>{expect(scorePair(e({requirements:[{status:"pass",weight:1},{status:"unavailable",weight:1}]})).baseline.requirementCompletion.measurableMaximum).toBe(12.5);});
it("[S06] instruction denominator",()=>{expect(scorePair(e({rules:[{status:"pass",weight:1},{status:"fail",weight:3}]})).baseline.instructionCompliance.score).toBe(5);});
it("[S07] instruction measurable maximum",()=>{expect(scorePair(e({rules:[{status:"pass",weight:1},{status:"unavailable",weight:3}]})).baseline.instructionCompliance.measurableMaximum).toBe(5);});
it("[S08] explicit fail measurable",()=>{const x=scorePair(e({correctness:[{status:"fail",weight:1}]})).baseline; expect(x.correctness).toMatchObject({score:0,measurableMaximum:40});});
it("[S09] unavailable limitation",()=>{expect(scorePair(e({correctness:[{status:"unavailable",weight:1}]})).baseline.limitations).toContain("EVIDENCE_UNAVAILABLE");});
it("[S10] error invalid",()=>{const p=scorePair(e({correctness:[{status:"error",weight:1}]})); expect(resolveStatus("valid",p,true)).toBe("invalid");});
it("[S11] expected full focus",()=>{expect(scorePair(e()).baseline.changeFocus.score).toBe(10);});
it("[S12] unnecessary proportional",()=>{expect(scorePair(e({changes:{expectedPaths:["a"],unnecessaryPaths:["b"]}})).baseline.changeFocus.score).toBe(5);});
it("[S13] protected zero",()=>{expect(scorePair(e({changes:{protectedPathViolations:["x"]}})).baseline.changeFocus.score).toBe(0);});
it("[S14] missing path zero",()=>{expect(scorePair(e({changes:{missingRequiredChangedPaths:["x"]}})).baseline.changeFocus.score).toBe(0);});
it("[S15] ignored no penalty",()=>{expect(scorePair(e({changes:{ignoredPaths:["x"]}})).baseline.changeFocus.score).toBe(10);});
it("[S16] no change zero",()=>{expect(scorePair(e({changes:{expectedPaths:[],unnecessaryPaths:[]}})).baseline.changeFocus.score).toBe(0);});
it("[S17] equal tokens",()=>{const p=scorePair(e({totalTokens:3})); expect(p.baseline.tokenEfficiency.score).toBe(3); expect(p.camarade.tokenEfficiency.score).toBe(3);});
it("[S18] ratio tokens",()=>{const p=scorePair(e({totalTokens:2}),e({totalTokens:4})); expect(p.baseline.tokenEfficiency.score).toBe(3); expect(p.camarade.tokenEfficiency.score).toBe(1.5);});
it("[S19] zero tokens",()=>{const p=scorePair(e({totalTokens:0}),e({totalTokens:4})); expect(p.baseline.tokenEfficiency.score).toBe(3);});
it("[S20] missing tokens",()=>{const p=scorePair(e()); expect(p.baseline.tokenEfficiency.measurableMaximum).toBe(0);});
it("[S21] equal runtime",()=>{const p=scorePair(e({agentDurationMs:2})); expect(p.baseline.runtimeEfficiency.score).toBe(2);});
it("[S22] ratio runtime",()=>{const p=scorePair(e({agentDurationMs:2}),e({agentDurationMs:4})); expect(p.camarade.runtimeEfficiency.score).toBe(1);});
it("[S23] missing runtime",()=>{expect(scorePair(e()).baseline.runtimeEfficiency.measurableMaximum).toBe(0);});
it("[S24] perfect total",()=>{const p=scorePair(e({totalTokens:1,agentDurationMs:1}),e({totalTokens:1,agentDurationMs:1})); expect(p.baseline.total).toBe(100);});
it("[S25] valid status",()=>{const p=scorePair(e({totalTokens:1,agentDurationMs:1}),e({totalTokens:1,agentDurationMs:1})); expect(resolveStatus("valid",p)).toBe("valid");});
it("[S26] limited status",()=>{expect(resolveStatus("limited",scorePair(e()))).toBe("limited");});
it("[S27] invalid status",()=>{expect(resolveStatus("invalid",scorePair(e()))).toBe("invalid");});
it("[S28] positive tie",()=>{const p=scorePair(e({totalTokens:1,agentDurationMs:1}),e({totalTokens:1,agentDurationMs:1})); expect(resolveOutcome(p.baseline,p.camarade,"valid").outcome).toBe("tie");});
it("[S29] negative tie",()=>{expect(resolveOutcome({...scorePair(e()).baseline,total:50},{...scorePair(e()).camarade,total:51},"valid").outcome).toBe("tie");});
it("[S30] win",()=>{const p=scorePair(e({correctness:[{status:"fail",weight:1}],totalTokens:1,agentDurationMs:1}),e({totalTokens:1,agentDurationMs:1})); expect(resolveOutcome(p.baseline,p.camarade,"valid").outcome).toBe("win");});
it("[S31] regression",()=>{const p=scorePair(e({totalTokens:1,agentDurationMs:1}),e({correctness:[{status:"fail",weight:1}],totalTokens:1,agentDurationMs:1})); expect(resolveOutcome(p.baseline,p.camarade,"valid").outcome).toBe("regression");});
it("[S32] mandatory correctness override",()=>{expect(resolveMaterialOverride({condition:"baseline",mandatoryCorrectnessFailIds:["b"]},{condition:"camarade"},"valid")?.favoredCondition).toBe("camarade");});
it("[S33] material rule override",()=>{expect(resolveMaterialOverride({condition:"baseline",materialRuleFailIds:["b"]},{condition:"camarade"},"valid")?.type).toBe("material-rule");});
it("[S34] mandatory requirement override",()=>{expect(resolveMaterialOverride({condition:"baseline",mandatoryRequirementFailIds:["b"]},{condition:"camarade"},"valid")?.type).toBe("mandatory-requirement");});
it("[S35] override priority",()=>{expect(resolveMaterialOverride({condition:"baseline",mandatoryCorrectnessFailIds:["b"],materialRuleFailIds:["r"]},{condition:"camarade"},"valid")?.type).toBe("mandatory-correctness");});
it("[S36] equal failures numeric",()=>{expect(resolveMaterialOverride({condition:"baseline",materialRuleFailIds:["b"]},{condition:"camarade",materialRuleFailIds:["c"]},"valid")).toBeNull();});
it("[S37] raw precision",()=>{const p=scorePair(e({totalTokens:2}),e({totalTokens:3})); expect(p.baseline.tokenEfficiency.score).toBe(3);});
it("[S38] display rounding source",()=>{expect(scorePair(e()).baseline.total).toBe(95);});
it("[S39] limited no outcome",()=>{const p=scorePair(e()); expect(resolveOutcome(p.baseline,p.camarade,"limited").outcome).toBeNull();});
it("[S40] safe score object",()=>{expect(JSON.stringify(scorePair(e()))).not.toMatch(/\/(Users|tmp)\//);});
it("[S41] scoring remains a pure calculation",()=>{const input=e(); const before=JSON.stringify(input); scorePair(input); expect(JSON.stringify(input)).toBe(before);});
it("[S42] score artifact conditions are explicit",()=>{const pair=scorePair(e()); expect([pair.baseline.condition,pair.camarade.condition]).toEqual(["baseline","camarade"]);});
it("[S43] score categories expose finite values",()=>{const score=scorePair(e()).baseline; expect([score.total,score.measurableMaximum,score.scoreOutOf].every(Number.isFinite)).toBe(true);});
it("[S44] paired references use the same score scale",()=>{const pair=scorePair(e()); expect(pair.baseline.scoreOutOf).toBe(pair.camarade.scoreOutOf);});
it("[S45] scoring performs no execution orchestration",()=>{expect(scorePair(e()).baseline).not.toHaveProperty("exitCode");});
});
