import { describe, expect, it } from "vitest";
import { evaluateTask } from "../src/evaluate/evaluate-task.js";
import { DashboardRunSchema } from "../src/dashboard/contract.js";
import { renderDashboardRun } from "../src/evaluate/render-dashboard-run.js";
import { mkdtemp, mkdir, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
const files=async(dir:string,status:"valid"|"limited"|"invalid",outcome:any)=>{await mkdir(join(dir,"scoring"),{recursive:true});await mkdir(join(dir,"explanation"),{recursive:true});await writeFile(join(dir,"scoring/comparison.json"),JSON.stringify({experimentId:"cmp-1",status,outcome,limitations:["fixture"],simulationLabel:"simulation"}));for(const n of ["baseline-score.json","camarade-score.json"])await writeFile(join(dir,"scoring",n),JSON.stringify({condition:n.startsWith("base")?"baseline":"camarade"}));await writeFile(join(dir,"experiment-result.json"),JSON.stringify({startingState:{repositoryPath:process.cwd(),startingCommit:"abc"}}));await writeFile(join(dir,"explanation/instruction-impacts.json"),JSON.stringify({records:[]}));};
async function run(status:"valid"|"limited"|"invalid",outcome:any){const dir=await mkdtemp(join(tmpdir(),"camarade-eval-"));await files(dir,status,outcome);const stages:string[]=[];let configLoads=0;const result=await evaluateTask({repositoryPath:process.cwd(),task:"fixture task",controllerRoot:join(dir,"controller"),confirmExecution:true},{loadConfig:async()=>{configLoads++;return {experiment:{instructionMode:"augmentation",executionOrder:"baseline-first",codex:{executable:"fixture",timeoutSeconds:1,arguments:[],environmentAllowlist:[]}},configPath:null,validationCommands:[],timeoutSeconds:1}},experiment:async()=>{stages.push("stage-5 (includes stage-3/4)");return {summaryPath:join(dir,"experiment-summary.json"),startingState:{repositoryPath:process.cwd(),startingCommit:"abc"},prepared:{layout:{experimentDirectory:dir}}} as any},measure:async()=>{stages.push("stage-6");return {} as any},explain:async()=>{stages.push("stage-7");return {} as any}});return {result,stages,configLoads};}
describe("S8-02 authoritative pipeline",()=>{
it("[C14] full deterministic Stage 3–7 pipeline",async()=>{const x=await run("valid","win");expect(DashboardRunSchema.safeParse(x.result).success).toBe(true);expect(x.result.comparisonId).toBe("cmp-1");expect(x.result.conditions.map(c=>c.condition)).toEqual(["baseline","camarade"]);expect({simulation:x.result.simulation,realModel:x.result.realModel,network:x.result.network}).toEqual({simulation:true,realModel:false,network:false})});
it("[C15] execute every required stage once",async()=>{const x=await run("valid","win");expect(x.configLoads).toBe(1);expect(x.stages).toEqual(["stage-5 (includes stage-3/4)","stage-6","stage-7"])});
it("[C16] fatal stage failure stops later stages",async()=>{let measure=0,explain=0;await expect(evaluateTask({repositoryPath:process.cwd(),task:"x",controllerRoot:"/tmp/c",confirmExecution:true},{loadConfig:async()=>({experiment:{} as any,configPath:null,validationCommands:[],timeoutSeconds:1}),experiment:async()=>{throw new Error("fatal")},measure:async()=>{measure++;return {} as any},explain:async()=>{explain++;return {} as any}})).rejects.toThrow("fatal");expect({measure,explain}).toEqual({measure:0,explain:0})});
it("[C17] valid result preserves Stage 6 outcome",async()=>{for(const outcome of ["win","tie","regression"]){expect((await run("valid",outcome)).result.outcome).toBe(outcome)}});
it("[C18] limited result declares no winner",async()=>{const r=(await run("limited",null)).result;expect(r.status).toBe("limited");expect(r.outcome).toBeNull();expect(renderDashboardRun(r)).toContain("No outcome — limited evidence");expect(renderDashboardRun(r)).not.toMatch(/Camarade wins|Camarade regression|Tie/)});
it("[C19] invalid result declares no winner",async()=>{const r=(await run("invalid",null)).result;expect(r.status).toBe("invalid");expect(r.outcome).toBeNull();expect(renderDashboardRun(r)).toContain("No outcome — invalid experiment")});
it("[C20] human output agrees with DashboardRun",async()=>{const r=(await run("valid","win")).result;const text=renderDashboardRun(r);expect(text).toContain(`Task: ${r.task}`);expect(text).toContain(`Comparison ID: ${r.comparisonId}`);expect(text).toContain("Outcome: Camarade wins");expect(text).toContain("Baseline score: unavailable");expect(text).toContain("Camarade score: unavailable");expect(text).toContain("This result proves deterministic pipeline behavior only. It is not real benchmark evidence or an agent-quality claim.")});
it("[C21] JSON output validates with no extra stdout",async()=>{const r=(await run("valid","win")).result;const lines=JSON.stringify(r).split("\n");expect(lines).toHaveLength(1);expect(DashboardRunSchema.parse(JSON.parse(lines[0]!))).toEqual(r)});
});
