import {describe,it,expect} from "vitest";import {mkdtemp,mkdir,writeFile,symlink} from "node:fs/promises";import {join} from "node:path";import {tmpdir} from "node:os";import {SafeDashboardRunRepository,MAX_DASHBOARD_RUN_BYTES} from "../src/evaluate/run-store.js";
const fixture=async()=>JSON.parse(await (await import("node:fs/promises")).readFile(join(process.cwd(),"fixtures/stage-8/dashboard/valid-camarade-win.json"),"utf8"));const setup=async()=>{const r=await mkdtemp(join(tmpdir(),"s8-"));await mkdir(join(r,".camarade/runs/x"),{recursive:true});await writeFile(join(r,".camarade/runs/x/dashboard-run.json"),JSON.stringify({...await fixture(),comparisonId:"x"}));return r};
describe("S8-04 repository",()=>{it("[S8S02] list",async()=>expect((await new SafeDashboardRunRepository(await setup()).listRuns()).length).toBe(1));it("[S8S03] detail",async()=>expect((await new SafeDashboardRunRepository(await setup()).getRun("x")).comparisonId).toBe("x"));it("[S8S05] unsafe ID",async()=>await expect(new SafeDashboardRunRepository(await setup()).getRun("../x")).rejects.toMatchObject({code:"UNSAFE_COMPARISON_ID"}));it("[S8S06] unknown ID",async()=>await expect(new SafeDashboardRunRepository(await setup()).getRun("nope")).rejects.toMatchObject({code:"UNKNOWN_COMPARISON_ID"}));it("[S8S07] unsupported persisted run",async()=>{const r=await setup();await writeFile(join(r,".camarade/runs/x/dashboard-run.json"),"{}");await expect(new SafeDashboardRunRepository(r).getRun("x")).rejects.toMatchObject({code:"UNSUPPORTED_ARTIFACT_VERSION"})});it("[S8S08] corrupt list entry skipped",async()=>{const r=await setup();await mkdir(join(r,".camarade/runs/bad"));await writeFile(join(r,".camarade/runs/bad/dashboard-run.json"),"no");expect((await new SafeDashboardRunRepository(r).listRuns()).map(x=>x.comparisonId)).toEqual(["x"])});it("[S8S09] oversized run",async()=>{const r=await setup();await writeFile(join(r,".camarade/runs/x/dashboard-run.json"),Buffer.alloc(MAX_DASHBOARD_RUN_BYTES+1));await expect(new SafeDashboardRunRepository(r).getRun("x")).rejects.toMatchObject({code:"DASHBOARD_ARTIFACT_TOO_LARGE"})});it("[S8S10] run symlink",async()=>{const r=await mkdtemp(join(tmpdir(),"s8-link-"));await mkdir(join(r,".camarade/runs"),{recursive:true});await symlink("/tmp",join(r,".camarade/runs/x"));await expect(new SafeDashboardRunRepository(r).getRun("x")).rejects.toMatchObject({code:"UNKNOWN_COMPARISON_ID"})});});

describe("S8-04 public persisted evidence", () => {
  it("skips and rejects schema-valid runs containing private paths", async () => {
    const root = await setup();
    const path = join(root, ".camarade/runs/x/dashboard-run.json");
    const run = JSON.parse(await (await import("node:fs/promises")).readFile(path, "utf8"));
    await writeFile(path, JSON.stringify({ ...run, task: "Investigate /private/controller/log.txt" }));
    const corrupt: Array<{ entry: string; code?: string }> = [];
    await expect(new SafeDashboardRunRepository(root).listRuns((entry, code) => corrupt.push({ entry, code }))).resolves.toEqual([]);
    expect(corrupt).toEqual([{ entry: "x", code: "INVALID_RUN" }]);
    await expect(new SafeDashboardRunRepository(root).getRun("x")).rejects.toMatchObject({ code: "INVALID_RUN" });
  });
});
