import { describe, expect, it } from "vitest";
import { execFile as execFileCallback } from "node:child_process";
import { promisify } from "node:util";
import { mkdtemp, mkdir, readFile, rm, unlink, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
const execFile=promisify(execFileCallback);
const pkg=async()=>JSON.parse(await readFile("package.json","utf8"));
describe("S8-02 package",()=>{
it("[S8C27] compiled bin executes without tsx",async()=>{await execFile("npm",["run","build"],{cwd:process.cwd(),env:{...process.env}});const r=await execFile(process.execPath,["dist/src/bin/camarade.js","--help"],{cwd:process.cwd(),env:{...process.env,PATH:"/usr/bin:/bin"}});expect(r.stdout).toMatch(/Usage: camarade/);expect(r.stderr).toBe("");},30000);
it("[S8C28] npm tarball help, runs, and show smoke tests",async()=>{const root=await mkdtemp(join(tmpdir(),"camarade-tarball-"));let tarball:string|undefined;try{await execFile("npm",["run","build"],{cwd:process.cwd()});const packed=await execFile("npm",["pack","--silent"],{cwd:process.cwd()});tarball=packed.stdout.trim().split(/\s+/).pop();expect(tarball).toMatch(/\.tgz$/);const controller=join(root,"controller");const run=join(controller,".camarade","runs","win-001");await mkdir(run,{recursive:true});const fixture=await readFile(join(process.cwd(),"fixtures/stage-8/dashboard/valid-camarade-win.json"),"utf8");await writeFile(join(run,"dashboard-run.json"),fixture);const env={...process.env,CI:"1"};const runResult=await execFile("npx",["--yes",`./${tarball}`,"runs","--controller-root",controller,"--json"],{cwd:process.cwd(),env,timeout:20000});const showResult=await execFile("npx",["--yes",`./${tarball}`,"show","win-001","--controller-root",controller,"--json"],{cwd:process.cwd(),env,timeout:20000});const help=await execFile("npx",["--yes",`./${tarball}`,"--help"],{cwd:process.cwd(),env,timeout:20000});expect(help.stdout).toMatch(/Usage: camarade/);const badShow=await execFile("npx",["--yes",`./${tarball}`,"show","../escape","--controller-root",controller],{cwd:process.cwd(),env,timeout:20000}).then(()=>{throw new Error("unsafe show succeeded")},(error:{code?:number;stderr?:string})=>error);expect(badShow.code).toBe(1);expect(String(badShow.stderr)).toContain("Problem: Unsafe comparison ID.");expect(String(badShow.stderr)).not.toMatch(/    at |\/Users\//);expect(JSON.parse(runResult.stdout)[0].comparisonId).toBe("win-001");const shown=JSON.parse(showResult.stdout);expect(shown.comparisonId).toBe("win-001");for(const output of [runResult.stdout,showResult.stdout])expect(output).not.toMatch(/\/Users\/|\/private\/|system prompt|secret/i)}finally{if(tarball)await unlink(join(process.cwd(),tarball)).catch(()=>{});await rm(root,{recursive:true,force:true})}},30000);
});
