import type { EvidenceSource, InstructionParseResult, RepositoryRule, SourceSegment, RulePolarity, RuleStrength } from "./model.js";
import { createStableId } from "./stable-id.js";
import { resolveRuleScope } from "./resolve-rule-scope.js";

const clean = (raw: string): string => raw.trim().replace(/^(?:[-*+]\s+|\d+[.)]\s+)/, "").trim().replace(/\.$/, "").trim();
const classify = (s: string): [RulePolarity, RuleStrength] | undefined => {
  const tests: Array<[RegExp, RulePolarity, RuleStrength]> = [[/\bmust not\b|\bnever\b|\bonly\b[\s\S]*\bmust not\b/i, "prohibit", "absolute"], [/\bdo not(?: use)?\b/i, "prohibit", "required"], [/\bshould not\b|\bavoid\b/i, "avoid", "preferred"], [/\balways\b|\bonly\b(?!\s+for\b)/i, "require", "absolute"], [/\bmust\b|(?<!\bmay )(?<!\bshould )\buse\b|\bimplement\b|\brequire\b/i, "require", "required"], [/\bshould\b|\bprefer\b|\brecommended\b/i, "prefer", "preferred"], [/\bmay\b|\ballow(?:ed)?\b/i, "allow", "permitted"]];
  for (const [re, p, st] of tests) if (re.test(s)) return [p, st]; return undefined;
};
const action = (s: string): string => s.toLowerCase().replace(/[`*_]/g, "").replace(/-/g, " ").replace(/^(?:must not|do not|should not|never|must|should|may|always|prefer|use|implement|require|recommended|avoid|only)\b\s*/i, "").replace(/\b(?:a|an|the)\b\s*/g, "").replace(/\s+/g, " ").replace(/[.!?]+$/, "").trim();
const subject = (a: string): string => { const m = a.match(/\bfor\b([\s\S]*)/i) || a.match(/\bin\b([\s\S]*)/i) || a.match(/\bunder\b([\s\S]*)/i); let v = m ? m[1] : a; if (!m) v = a.replace(/^(?:add|use|implement|require|prefer|avoid|allow|write|keep|run)\s+/i, ""); return v.toLowerCase().replace(/-/g, " ").replace(/^(?:a|an|the)\s+/, "").replace(/[^a-z0-9 ]+/g, " ").replace(/\s+/g, " ").trim() || "repository"; };
export function parseInstructionSegments(sources: readonly EvidenceSource[], segments: readonly SourceSegment[]): InstructionParseResult {
  const byId = new Map(sources.map((s) => [s.id, s])); const evidence = []; const rules: RepositoryRule[] = []; const skipped = [];
  for (const segment of segments) { if (segment.kind !== "directive") continue; const source = byId.get(segment.sourceId); if (!source) { skipped.push({ segmentId: segment.id, reason: "Source not found" }); continue; } const statement = clean(segment.rawExcerpt); if (!statement) { skipped.push({ segmentId: segment.id, reason: "Empty normalized statement" }); continue; } const classified = classify(statement); if (!classified) { skipped.push({ segmentId: segment.id, reason: "Directive polarity could not be classified" }); continue; } const [polarity, strength] = classified; const evidenceId = createStableId("evidence", [source.id, segment.startLine, segment.endLine, segment.excerptHash]); evidence.push({ id: evidenceId, sourceId: source.id, startLine: segment.startLine, endLine: segment.endLine, excerpt: segment.rawExcerpt, excerptHash: segment.excerptHash }); const normalizedAction = action(statement); const normalizedSubject = subject(normalizedAction); const scope = resolveRuleScope({ statement, sourceRelativePath: source.relativePath }); rules.push({ id: createStableId("rule", [statement, normalizedSubject, normalizedAction, polarity, strength, scope, evidenceId]), statement, normalizedSubject, normalizedAction, polarity, strength, scope, evidenceIds: [evidenceId] }); }
  evidence.sort((a, b) => a.id.localeCompare(b.id)); rules.sort((a, b) => a.id.localeCompare(b.id)); skipped.sort((a, b) => a.segmentId.localeCompare(b.segmentId) || a.reason.localeCompare(b.reason)); return { evidence, rules, skipped };
}
