import { lstat, readFile, stat, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { isAbsolute, relative, resolve } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { createHash } from "node:crypto";
import { buildDashboardRun } from "../dashboard/build-dashboard-run.js";
import { DashboardRunSchema, type DashboardRun, type DashboardCondition } from "../dashboard/contract.js";
import { loadRunConfig, type LoadedRunConfigWithContext } from "../config/load-run-config.js";
import { runFairExperiment, type RunFairExperimentOptions } from "../experiment/run-fair-experiment.js";
import { measureCompletedExperiment, type MeasureExperimentMcpResult } from "../evaluation/measure-completed-experiment.js";
import { explainCompletedExperiment } from "../explanation/explain-completed-experiment.js";
import { EvaluateTaskError } from "./errors.js";
import { isPortableAbsolutePath } from "../core/path-portability.js";
const git = promisify(execFile);
export interface EvaluateTaskRequest { repositoryPath?: string; task?: string; taskFile?: string; controllerRoot?: string; confirmExecution?: boolean; json?: boolean }
export interface EvaluateTaskDependencies { loadConfig?: typeof loadRunConfig; experiment?: typeof runFairExperiment; measure?: typeof measureCompletedExperiment; explain?: typeof explainCompletedExperiment; confirm?: (message: string) => Promise<boolean>; isInteractive?: () => boolean; now?: () => Date }
async function gitRoot(candidate: string): Promise<string> { const root=resolve(candidate);const s=await stat(root).catch(()=>undefined);if(!s?.isDirectory())throw new EvaluateTaskError("INVALID_REPOSITORY","Repository must be an existing directory.");try{return(await git("git",["-C",root,"rev-parse","--show-toplevel"])).stdout.trim()}catch{throw new EvaluateTaskError("INVALID_REPOSITORY","Repository is not a Git worktree.")} }
async function taskOf(r:EvaluateTaskRequest):Promise<string>{if((r.task===undefined)===(r.taskFile===undefined))throw new EvaluateTaskError("TASK_SOURCE","Exactly one of --task or --task-file is required.");if(r.task!==undefined){if(!r.task.trim()||r.task.includes("\0"))throw new EvaluateTaskError("INVALID_TASK","Task must be non-empty and contain no null bytes.");return r.task.trim()}const p=resolve(r.taskFile!);const m=await lstat(p).catch(()=>undefined);if(!m?.isFile()||m.isSymbolicLink())throw new EvaluateTaskError("INVALID_TASK_FILE","Task file must be a regular non-symlink file.");const t=(await readFile(p,"utf8")).trim();if(!t||t.includes("\0"))throw new EvaluateTaskError("INVALID_TASK","Task file must be non-empty and contain no null bytes.");return t}
export function controllerRoot(requested?:string):string{const home=process.env.CAMARADE_HOME;const candidate=requested??(home&&isPortableAbsolutePath(home)?home:resolve(homedir(),".camarade"));return isPortableAbsolutePath(candidate)?candidate:resolve(candidate)}
const ref=(v:unknown,fallback:string)=>typeof v==="string"&&!isAbsolute(v)&&!v.includes("\\")&&!v.split("/").includes("..")?v:fallback;
const safe=(v:unknown,fallback="persisted-evidence")=>typeof v==="string"&&!isAbsolute(v)&&!v.includes("..")?v:fallback;
const evidence=(items:any[])=>items.map((e:any,i:number)=>({evidenceId:String(e.evidenceId??`evidence-${i+1}`),relation:e.relation??"supporting",strength:e.strength??"insufficient",explanation:String(e.explanation??"Persisted evidence reference."),sourceRef:safe(e.sourceRef),...(e.sourceRange?{sourceRange:e.sourceRange}:{}),...(e.excerpt?{excerpt:String(e.excerpt)}:{})}));
function scores(raw:any):any[]{const fields=["correctness","requirementCompletion","instructionCompliance","changeFocus","efficiency","tokenEfficiency","runtimeEfficiency"];const aliases:any={requirementCompletion:"requirement-completion",instructionCompliance:"instruction-compliance",changeFocus:"change-focus",tokenEfficiency:"token-efficiency",runtimeEfficiency:"runtime-efficiency"};return fields.map(key=>{const x=raw?.[key];const value=typeof x?.score==="number"?x.score:typeof x?.value==="number"?x.value:null;return {category:aliases[key]??key,value,status:value===null?"unavailable":"measured",evidence:[]}}).filter((x:any)=>["correctness","requirement-completion","instruction-compliance","change-focus","efficiency"].includes(x.category))}
function condition(raw:any,conditionId:"baseline"|"camarade",status:any,explanation:any):DashboardCondition{const records=Array.isArray(explanation?.records)?explanation.records:[];const impacts=records.map((r:any,i:number)=>({instructionId:String(r.instruction?.instructionId??r.instructionId??`instruction-${i+1}`),classification:r.alignment?.classification??"unresolved",direction:r.impact?.direction??"unknown",evidenceStrength:r.evidenceStrength??"insufficient",summary:String(r.impact?.explanation??"Persisted instruction impact evidence."),explanation:String(r.impact?.explanation??"Persisted instruction impact evidence."),evidence:evidence(Array.isArray(r.evidence)?r.evidence:[]),limitations:Array.isArray(r.limitations)?r.limitations:[]}));const checks=Array.isArray(raw?.checks)?raw.checks:Array.isArray(raw?.checkResults)?raw.checkResults:[];const metrics=Array.isArray(raw?.metrics)?raw.metrics:[];const files=Array.isArray(raw?.changedFiles)?raw.changedFiles:Array.isArray(raw?.changes?.changedPaths)?raw.changes.changedPaths:[];return {condition:conditionId,status,summary:String(raw?.summary??`${conditionId} condition`),scores:scores(raw),problems:Array.isArray(raw?.problems)?raw.problems:[],context:Array.isArray(raw?.context)?raw.context:[],checks,metrics,dependencyChanges:Array.isArray(raw?.dependencyChanges)?raw.dependencyChanges:[],fileChanges:files.map((p:string,i:number)=>({fileChangeId:`file-${i+1}`,path:safe(p),change:"modified",summary:"Persisted changed-file evidence.",evidence:[]})),impacts,evidenceQuality:impacts.length?"strongly-supported":"insufficient"}}
async function mapPersisted(directory:string,task:string,startedAt:string,simulation:boolean):Promise<DashboardRun>{const raws=new Map<string,string>();const loadRaw=async(rel:string,fallback?:string)=>{const raw=fallback===undefined?await readFile(resolve(directory,rel),"utf8"):await readFile(resolve(directory,rel),"utf8").catch(()=>fallback);raws.set(rel,raw);return raw};const cmp:any=JSON.parse(await loadRaw("scoring/comparison.json"));const base:any=JSON.parse(await loadRaw("scoring/baseline-score.json"));const cam:any=JSON.parse(await loadRaw("scoring/camarade-score.json"));const result:any=JSON.parse(await readFile(resolve(directory,"experiment-result.json"),"utf8"));const expRaw=await loadRaw("explanation/instruction-impacts.json","{}");const explanation:any=JSON.parse(expRaw);const status=cmp.status as any;const name=String(result.startingState?.repositoryPath??"repository").split(/[\\/]/).pop()??"repository";const run=buildDashboardRun({schemaVersion:"stage-8-dashboard.v1",comparisonId:String(cmp.experimentId),task,repository:{name:name.replace(/[^A-Za-z0-9._:-]/g,"-")||"repository",startingCommit:String(result.startingState?.startingCommit??"unknown").replace(/[^A-Za-z0-9._:-]/g,"-")||"unknown",branch:"unknown"},timestamps:{startedAt:new Date(startedAt).toISOString(),completedAt:new Date().toISOString()},status,outcome:status==="valid"?cmp.outcome:null,progress:{stage:"complete",percent:100,summary:"Complete"},simulation,realModel:!simulation,network:false,conditions:[condition(base,"baseline",status,{}),condition(cam,"camarade",status,explanation)],limitations:Array.isArray(cmp.limitations)?cmp.limitations:[],artifacts:["scoring/comparison.json","scoring/baseline-score.json","scoring/camarade-score.json","explanation/instruction-impacts.json"].map(p=>({artifactId:p.replace(/[^A-Za-z0-9]/g,"-"),kind:p.includes("explanation")?"explanation":"scoring",path:p,hash:createHash("sha256").update(raws.get(p)??"").digest("hex")})),errors:[]});await writeFile(resolve(directory,"dashboard-run.json"),`${JSON.stringify(run)}\n`,{flag:"w",encoding:"utf8"});return run}
export async function evaluateTask(r:EvaluateTaskRequest,d:EvaluateTaskDependencies={}):Promise<DashboardRun>{const repo=await gitRoot(r.repositoryPath??process.cwd());const task=await taskOf(r);const root=controllerRoot(r.controllerRoot);const rel=relative(repo,root);if(!rel||(!rel.startsWith("..")&&!isAbsolute(rel)))throw new EvaluateTaskError("CONTROLLER_INSIDE_REPOSITORY","Controller root must be outside the repository.");if(!r.confirmExecution){if(r.json||!(d.isInteractive?.()??Boolean(process.stdin.isTTY)))throw new EvaluateTaskError("EXECUTION_NOT_CONFIRMED","Non-interactive and JSON execution requires --confirm-execution.");if(!await(d.confirm??(async()=>false))("Execution creates comparison artifacts. Continue? [y/N] "))throw new EvaluateTaskError("EXECUTION_NOT_CONFIRMED","Execution was not confirmed.")}const config=await(d.loadConfig??loadRunConfig)(repo);if(!config.experiment)throw new EvaluateTaskError("EXPERIMENT_CONFIG_REQUIRED","experiment configuration is required in camarade.run.yaml; explicit legacy --adapter mode is required otherwise.");const e=await(d.experiment??runFairExperiment)({repositoryPath:repo,task,controllerRoot:root},config);const directory=e.prepared?.layout.experimentDirectory;if(!directory)throw new EvaluateTaskError("EXPERIMENT_ARTIFACT_MISSING","Experiment directory was not returned.");await(d.measure??measureCompletedExperiment)({experimentDirectory:directory});await(d.explain??explainCompletedExperiment)({experimentDirectory:directory});return mapPersisted(directory,task,new Date().toISOString(),true)}
export async function loadDashboardRun(directory:string):Promise<DashboardRun>{return DashboardRunSchema.parse(JSON.parse(await readFile(resolve(directory,"dashboard-run.json"),"utf8")))}
