import { lstat, readFile, stat, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import { isAbsolute, relative, resolve } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { createHash } from "node:crypto";
import { buildDashboardRun } from "../dashboard/build-dashboard-run.js";
import { DashboardRunSchema, type DashboardRun, type DashboardCondition } from "../dashboard/contract.js";
import { loadRunConfig, type LoadedRunConfigWithContext } from "../config/load-run-config.js";
import { runFairExperiment, type RunFairExperimentOptions } from "../experiment/run-fair-experiment.js";
import { measureCompletedExperiment, type MeasureExperimentMcpResult } from "../evaluation/measure-completed-experiment.js";
import { explainCompletedExperiment } from "../explanation/explain-completed-experiment.js";
import { EvaluateTaskError } from "./errors.js";
const git = promisify(execFile);
export interface EvaluateTaskRequest { repositoryPath?: string; task?: string; taskFile?: string; controllerRoot?: string; confirmExecution?: boolean; json?: boolean }
export interface EvaluateTaskDependencies { loadConfig?: typeof loadRunConfig; experiment?: typeof runFairExperiment; measure?: typeof measureCompletedExperiment; explain?: typeof explainCompletedExperiment; confirm?: (message: string) => Promise<boolean>; isInteractive?: () => boolean; now?: () => Date }
async function gitRoot(candidate: string): Promise<string> { const root=resolve(candidate);const s=await stat(root).catch(()=>undefined);if(!s?.isDirectory())throw new EvaluateTaskError("INVALID_REPOSITORY","Repository must be an existing directory.");try{return(await git("git",["-C",root,"rev-parse","--show-toplevel"])).stdout.trim()}catch{throw new EvaluateTaskError("INVALID_REPOSITORY","Repository is not a Git worktree.")} }
async function taskOf(r:EvaluateTaskRequest):Promise<string>{if((r.task===undefined)===(r.taskFile===undefined))throw new EvaluateTaskError("TASK_SOURCE","Exactly one of --task or --task-file is required.");if(r.task!==undefined){if(!r.task.trim()||r.task.includes("\0"))throw new EvaluateTaskError("INVALID_TASK","Task must be non-empty and contain no null bytes.");return r.task.trim()}const p=resolve(r.taskFile!);const m=await lstat(p).catch(()=>undefined);if(!m?.isFile()||m.isSymbolicLink())throw new EvaluateTaskError("INVALID_TASK_FILE","Task file must be a regular non-symlink file.");const t=(await readFile(p,"utf8")).trim();if(!t||t.includes("\0"))throw new EvaluateTaskError("INVALID_TASK","Task file must be non-empty and contain no null bytes.");return t}
export function controllerRoot(requested?:string):string{const home=process.env.CAMARADE_HOME;return resolve(requested??(home&&isAbsolute(home)?home:resolve(homedir(),".camarade")))}
const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(v)).digest("hex");
const ref=(v:unknown,fallback:string)=>typeof v==="string"&&!isAbsolute(v)&&!v.includes("\\")&&!v.split("/").includes("..")?v:fallback;
function scores(raw:any):any[]{const fields=["correctness","requirementCompletion","instructionCompliance","changeFocus","efficiency"];return fields.map((key)=>{const x=raw?.[key];const value=typeof x?.score==="number"?x.score:typeof x?.value==="number"?x.value:null;return {category:key==="requirementCompletion"?"requirement-completion":key==="instructionCompliance"?"instruction-compliance":key==="changeFocus"?"change-focus":key,value,status:value===null?"unavailable":"measured",evidence:[]}})}
function condition(raw:any,conditionId:"baseline"|"camarade",status:any,explanation:any):DashboardCondition{const records=Array.isArray(explanation?.records)?explanation.records:[];const impacts=records.map((r:any)=>({instructionId:String(r.instruction?.instructionId??r.instructionId??"instruction-unknown"),classification:r.alignment?.classification??"unresolved",direction:r.impact?.direction??"unknown",evidenceStrength:r.evidence?.length?"direct":"insufficient",summary:String(r.impact?.explanation??"Persisted instruction impact evidence."),evidence:[],limitations:Array.isArray(r.limitations)?r.limitations:[]}));return {condition:conditionId,status,summary:`${conditionId} condition`,scores:scores(raw),problems:[],context:[],checks:[],metrics:[],impacts,evidenceQuality:impacts.length?"strongly-supported":"insufficient"}}
async function mapPersisted(directory:string,task:string,startedAt:string,simulation:boolean):Promise<DashboardRun>{const cmp:any=JSON.parse(await readFile(resolve(directory,"scoring/comparison.json"),"utf8"));const base:any=JSON.parse(await readFile(resolve(directory,"scoring/baseline-score.json"),"utf8"));const cam:any=JSON.parse(await readFile(resolve(directory,"scoring/camarade-score.json"),"utf8"));const result:any=JSON.parse(await readFile(resolve(directory,"experiment-result.json"),"utf8"));const explanation:any=JSON.parse(await readFile(resolve(directory,"explanation/instruction-impacts.json"),"utf8")).records?JSON.parse(await readFile(resolve(directory,"explanation/instruction-impacts.json"),"utf8")):{};const status=cmp.status as "valid"|"limited"|"invalid";const run=buildDashboardRun({schemaVersion:"stage-8-dashboard.v1",comparisonId:String(cmp.experimentId),task,repository:{name:String(result.startingState?.repositoryPath??"repository").split(/[\\/]/).pop()??"repository",startingCommit:String(result.startingState?.startingCommit??"unknown"),branch:"unknown"},timestamps:{startedAt:new Date(startedAt).toISOString(),completedAt:new Date().toISOString()},status,outcome:status==="valid"?cmp.outcome:null,progress:{stage:"complete",percent:100,summary:"Complete"},simulation,realModel:!simulation,network:false,conditions:[condition(base,"baseline",status,{}),condition(cam,"camarade",status,explanation)],limitations:Array.isArray(cmp.limitations)?cmp.limitations:[],artifacts:["scoring/comparison.json","scoring/baseline-score.json","scoring/camarade-score.json","explanation/instruction-impacts.json"].map((p)=>({artifactId:p.replace(/[^A-Za-z0-9]/g,"-"),kind:p.includes("explanation")?"explanation":"scoring",path:p,hash:digest(p)})),errors:[]});await writeFile(resolve(directory,"dashboard-run.json"),`${JSON.stringify(run)}\n`,{flag:"w",encoding:"utf8"});return run}
export async function evaluateTask(r:EvaluateTaskRequest,d:EvaluateTaskDependencies={}):Promise<DashboardRun>{const repo=await gitRoot(r.repositoryPath??process.cwd());const task=await taskOf(r);const root=controllerRoot(r.controllerRoot);const rel=relative(repo,root);if(!rel||(!rel.startsWith("..")&&!isAbsolute(rel)))throw new EvaluateTaskError("CONTROLLER_INSIDE_REPOSITORY","Controller root must be outside the repository.");if(!r.confirmExecution){if(r.json||!(d.isInteractive?.()??Boolean(process.stdin.isTTY)))throw new EvaluateTaskError("EXECUTION_NOT_CONFIRMED","Non-interactive and JSON execution requires --confirm-execution.");if(!await(d.confirm??(async()=>false))("Execution creates comparison artifacts. Continue? [y/N] "))throw new EvaluateTaskError("EXECUTION_NOT_CONFIRMED","Execution was not confirmed.")}const config=await(d.loadConfig??loadRunConfig)(repo);if(!config.experiment)throw new EvaluateTaskError("EXPERIMENT_CONFIG_REQUIRED","experiment configuration is required in camarade.run.yaml; explicit legacy --adapter mode is required otherwise.");const e=await(d.experiment??runFairExperiment)({repositoryPath:repo,task,controllerRoot:root},config);const directory=e.prepared?.layout.experimentDirectory;if(!directory)throw new EvaluateTaskError("EXPERIMENT_ARTIFACT_MISSING","Experiment directory was not returned.");await(d.measure??measureCompletedExperiment)({experimentDirectory:directory});await(d.explain??explainCompletedExperiment)({experimentDirectory:directory});return mapPersisted(directory,task,new Date().toISOString(),true)}
export async function loadDashboardRun(directory:string):Promise<DashboardRun>{return DashboardRunSchema.parse(JSON.parse(await readFile(resolve(directory,"dashboard-run.json"),"utf8")))}
