import { copyFile, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { gzipSync } from "node:zlib";
import { build } from "esbuild";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const output = path.join(root, "plugins/camarade/mcp/server.mjs");

await mkdir(path.dirname(output), { recursive: true });
await build({
  entryPoints: [path.join(root, "src/mcp/start-server.ts")],
  outfile: output,
  bundle: true,
  format: "esm",
  platform: "node",
  target: "node20",
  minify: true,
  plugins: [{
    name: "external-typescript-runtime",
    setup(context) {
      context.onResolve({ filter: /^typescript$/ }, () => ({
        path: "./vendor/typescript.cjs",
        external: true
      }));
    }
  }],
  sourcemap: false,
  legalComments: "linked",
  banner: {
    js: [
      "// Generated by npm run build:plugin. Do not edit directly.",
      "import { createRequire as __createRequire } from 'node:module';",
      "const require = __createRequire(import.meta.url);"
    ].join("\n")
  }
});

const typescriptRoot = path.join(root, "plugins/camarade/mcp/vendor");
await mkdir(typescriptRoot, { recursive: true });
await copyFile(
  path.join(root, "node_modules/dictionary-en/license"),
  path.join(typescriptRoot, "dictionary-en-LICENSE.txt")
);
for (const [source, destination] of [
  ["LICENSE.txt", "typescript-LICENSE.txt"],
]) {
  await copyFile(
    path.join(root, "node_modules/typescript", source),
    path.join(typescriptRoot, destination)
  );
}

for (const [source, destination] of [
  [path.join(root, "node_modules/dictionary-en/index.aff"), "index.aff.gz"],
  [path.join(root, "node_modules/dictionary-en/index.dic"), "index.dic.gz"],
  [path.join(root, "node_modules/typescript/lib/typescript.js"), "typescript.cjs.gz"]
]) {
  const compressed = gzipSync(await readFile(source), { level: 9, mtime: 0 });
  await writeFile(path.join(typescriptRoot, destination), compressed);
}

console.log(`Built ${path.relative(root, output)}`);
