import { access, rm } from "node:fs/promises";
import path from "node:path";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StdioClientTransport } from "@modelcontextprotocol/sdk/client/stdio.js";

const root = path.resolve(import.meta.dirname, "..");
const fixture = path.resolve(root, "examples/intelligence-fixture");
const entry = path.resolve(root, "dist/src/mcp/start-server.js");
const requiredRecord = (value: unknown, label: string): Record<string, unknown> => { if (value === null || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label} is not an object`); return value as Record<string, unknown>; };
const textPayload = (value: unknown): Record<string, unknown> => { const response = requiredRecord(value, "tool response"); const content = response.content; if (!Array.isArray(content)) throw new Error("tool response content missing"); const item = content.find((entry) => requiredRecord(entry, "content item").type === "text"); if (!item) throw new Error("text content missing"); return requiredRecord(JSON.parse(String(requiredRecord(item, "text item").text)), "text payload"); };
async function main(): Promise<void> { await access(entry); const client = new Client({ name: "camarade-stage-4-verifier", version: "1.0.0" }); const transport = new StdioClientTransport({ command: process.execPath, args: [entry], cwd: root, stderr: "pipe" }); let controllerRoot: string | undefined; try { await client.connect(transport); const listed = await client.listTools(); if (!listed.tools.some(tool => tool.name === "camarade.compile_task_context") || !listed.tools.some(tool => tool.name === "camarade.run_fair_experiment") || !listed.tools.some(tool => tool.name === "camarade.measure_experiment")) throw new Error("required tool was not discovered"); const response = await client.callTool({ name: "camarade.compile_task_context", arguments: { repository_root: fixture, task: "Add rate limiting to the public search API" } }); if (response.isError) throw new Error("built server returned a tool error"); const payload = textPayload(response); const structured = requiredRecord(response.structuredContent, "structured content"); if (JSON.stringify(payload) !== JSON.stringify(structured)) throw new Error("text and structured payload differ"); if (payload.status !== "complete") throw new Error("built server did not return complete status"); for (const key of ["contract", "summary", "provenance", "artifacts"]) requiredRecord(payload[key], key); controllerRoot = String(payload.controller_root); for (const artifact of Object.values(requiredRecord(payload.artifacts, "artifacts"))) await access(String(artifact)); console.log("Stage 4 MCP verification: PASS"); console.log("Server: camarade 1.2.0"); console.log("Tool: camarade.compile_task_context"); console.log("Status: complete"); } finally { await client.close().catch(() => undefined); await transport.close().catch(() => undefined); if (controllerRoot && path.basename(controllerRoot).startsWith("camarade-controller-")) await rm(controllerRoot, { recursive: true, force: true }); } }
main().catch(() => { console.error("Stage 4 MCP verification failed."); process.exitCode = 1; });
