import { validateInstructionEvidenceBundle } from "./validate-instruction-evidence.js";
import { INSTRUCTION_EVIDENCE_SCHEMA_VERSION, type EvidenceReference } from "./instruction-evidence-types.js";
import { arr, identityOf, idOf, linkedIds, normalized, obj, refOf, text, type Obj } from "./instruction-impact-match.js";
import { matchInstructionChanges } from "./match-instruction-changes.js";
import { matchInstructionDependencies } from "./match-instruction-dependencies.js";
import { matchInstructionChecks } from "./match-instruction-checks.js";
import { compareInstructionConditions } from "./compare-instruction-conditions.js";
import { classifyAlignment } from "./instruction-impact-classify.js";
import { resolveInstructionImpact } from "./resolve-instruction-impact.js";
import type { InstructionImpactInput, InstructionImpactResult } from "./instruction-impact-types.js";
const refs = (items: Obj[], relation: "effect"|"supporting"|"contradicting", strength: "direct"|"strongly-supported"|"correlated"|"insufficient", explanation: string): EvidenceReference[] => items.map((x, i) => ({ evidenceId: `${relation}-${idOf(x) || "evidence"}-${i + 1}`, relation, strength, explanation, sourceRef: refOf(x) })).filter(x => x.sourceRef).sort((a,b) => a.evidenceId.localeCompare(b.evidenceId));
const explicitScope = (input: InstructionImpactInput, item: Obj) => { const r = obj(input.repository); const scope = obj(input as unknown as Obj).taskScope ?? r.taskScope ?? r.relevance; return records(scope, ["irrelevantInstructions", "excludedInstructions", "irrelevant", "excluded"]).some(x => linkedIds(x).includes(idOf(item)) || normalized(identityOf(x)) === normalized(identityOf(item))); };
const records = (v: unknown, keys: readonly string[]) => { const r = obj(v); return keys.flatMap(k => arr(r[k]).map(obj).filter(x => Object.keys(x).length > 0)); };
export function buildImpactExplanation(input: InstructionImpactInput): InstructionImpactResult {
  const raw = input.instructions.map((x, i) => { const r = obj(x); return { ...r, instructionId: idOf(r) || `instruction-${i + 1}`, identity: identityOf(r) || idOf(r) || `instruction-${i + 1}`, included: r.included !== false, provenance: obj(r.provenance) }; }).sort((a,b) => a.instructionId.localeCompare(b.instructionId) || normalized(a.identity).localeCompare(normalized(b.identity)));
  const seen = new Set<string>();
  const recordsOut = raw.map(item => {
    const id = item.instructionId, cond = compareInstructionConditions(id, input.baseline, input.optimized, item); const included = item.included; const duplicate = seen.has(normalized(item.identity)); seen.add(normalized(item.identity));
    const changes = [...matchInstructionChanges(id, input.baseline), ...matchInstructionChanges(id, input.optimized)]; const deps = [...matchInstructionDependencies(id, input.baseline), ...matchInstructionDependencies(id, input.optimized), ...matchInstructionDependencies(id, input.repository)]; const checks = [...matchInstructionChecks(id, input.baseline), ...matchInstructionChecks(id, input.optimized), ...matchInstructionChecks(id, input.repository)];
    const positive = checks.filter(x => ["pass", "passed", "preserved", "satisfied"].includes(text(x.status ?? x.result ?? x.outcome).toLowerCase()) && !x.failed); const negative = [...checks, ...deps].filter(x => ["fail", "failed", "violation", "unsupported", "forbidden"].some(s => text(x.status ?? x.result ?? x.outcome ?? x.kind).toLowerCase().includes(s))); const contradictory = checks.filter(x => x.contradicts === true || x.contradicting === true);
    const staleEvidence = [...changes, ...deps, ...checks].some(x => ["stale", "removed", "unsupported", "absent"].includes(text(x.status ?? x.state ?? x.intelligenceStatus).toLowerCase()));
    const activeReplacement = records(input.repository, ["facts", "repositoryFacts", "architectureFacts"]).some(x => ["active-replacement", "replacement", "current-architecture"].includes(text(x.kind ?? x.factType).toLowerCase()) && refOf(x));
    const stale = staleEvidence || (deps.some(x => ["removed", "unsupported", "absent"].includes(text(x.status ?? x.state ?? x.intelligenceStatus).toLowerCase())) && activeReplacement);
    const alignment = classifyAlignment({ included, irrelevant: explicitScope(input, item), duplicate, conflicting: contradictory.length > 0, stale, membership: cond.membership }); const resolution = resolveInstructionImpact(refs(positive, "effect", "direct", "Explicit linked passing check or rule.").map(x => ({ sourceRef: x.sourceRef, id: x.evidenceId })), [...negative], contradictory, input.experimentStatus);
    const evidence = [...refs(changes, "supporting", "correlated", "Explicit instruction-to-change linkage; change alone is non-causal."), ...refs(deps, "effect", negative.length ? "direct" : "correlated", "Explicit instruction-to-dependency linkage; dependency presence alone is non-causal."), ...refs(checks, negative.length || positive.length ? "effect" : "supporting", negative.length || positive.length ? "direct" : "correlated", "Explicit instruction-to-check or rule linkage."), ...refs(contradictory, "contradicting", "direct", "Contradictory structured evidence.")].sort((a,b) => a.evidenceId.localeCompare(b.evidenceId)).map((e, i) => ({ ...e, evidenceId: `${e.evidenceId}-${i + 1}` }));
    const direction = alignment.classification === "irrelevant" || alignment.classification === "duplicate" || alignment.classification === "conflicting" || alignment.classification === "unresolved" || input.experimentStatus === "invalid" ? "unknown" : alignment.classification === "stale" ? (cond.membership === "neither" ? "unknown" : negative.length ? resolution.direction : "unknown") : cond.membership === "both" && !negative.length ? "neutral" : resolution.direction;
    return { schemaVersion: INSTRUCTION_EVIDENCE_SCHEMA_VERSION, instruction: { instructionId: id, identity: item.identity, provenance: { sourceRef: refOf(item.provenance) || refOf(item) || "instructions" }, conditionMembership: cond.membership, included }, alignment, impact: { direction, explanation: direction === "helped" ? "Explicit linked positive evidence supports a bounded helpful impact." : direction === "hurt" ? "Explicit linked failed requirement or material rule supports a bounded harmful impact." : resolution.limitations[0] || (stale && cond.membership === "neither" ? "The stale instruction was not applied; no harm is inferred." : alignment.explanation) }, evidenceStrength: direction === "unknown" && evidence.length === 0 ? "insufficient" : resolution.strength, evidence, limitations: [...new Set([...resolution.limitations, ...(stale && cond.membership === "neither" ? ["The stale instruction was not applied in either condition; no harm is inferred."] : [])])], analysisStatus: input.experimentStatus === "invalid" ? "invalid" : input.experimentStatus === "limited" ? "limited" : alignment.classification === "unresolved" ? "unresolved" : "complete" };
  });
  return validateInstructionEvidenceBundle({ schemaVersion: INSTRUCTION_EVIDENCE_SCHEMA_VERSION, records: recordsOut });
}
