import { createHash } from "node:crypto";
import { lstat, mkdir, open, readFile, rename, rm, writeFile } from "node:fs/promises";
import { isAbsolute, join, relative, resolve, sep } from "node:path";
import { canonicalJson, sha256 } from "../context/context-serialization.js";
import { buildImpactExplanation } from "./build-impact-explanation.js";
import type { InstructionImpactInput, InstructionImpactResult } from "./instruction-impact-types.js";
import { validateInstructionEvidenceBundle } from "./validate-instruction-evidence.js";

export const EXPLANATION_FILES = ["instruction-impacts.json", "helped-instructions.json", "harmful-instructions.json", "unresolved-instructions.json", "explanation-summary.json", "REPORT.md"] as const;
export const EXPLANATION_INDEX = "evidence-index.json";
export const EXPLANATION_ERROR = "EXPLANATION_ARTIFACT_INVALID";
type Json = Record<string, unknown>;
export interface ExplanationIndexEntry { relativePath: string; kind: string; sha256: string; byteLength: number }
export interface ExplanationEvidenceIndex { schemaVersion: "s7-03.1"; experimentId: string; entries: ExplanationIndexEntry[]; aggregateHash: string }
export interface ExplanationArtifacts { directory: string; index: ExplanationEvidenceIndex; result: InstructionImpactResult; summary: Json; report: string }

function fail(message: string): never { throw new Error(`${EXPLANATION_ERROR}: ${message}`); }
function safeRef(value: unknown): value is string { return typeof value === "string" && value.length > 0 && !isAbsolute(value) && !value.includes("\\") && !value.includes("\0") && !value.split("/").some(p => p === "" || p === "." || p === "..") && !/^[A-Za-z]:[\\/]/u.test(value); }
function inside(root: string, candidate: string): boolean { const r = relative(resolve(root), resolve(candidate)); return r === "" || (r !== ".." && !r.startsWith(`..${sep}`) && !isAbsolute(r)); }
async function realDirectory(path: string, create = false): Promise<void> { if (create) await mkdir(path, { recursive: true }); const s = await lstat(resolve(path)).catch(e => { if ((e as NodeJS.ErrnoException).code === "ENOENT") fail("missing directory"); throw e; }); if (!s.isDirectory() || s.isSymbolicLink()) fail("path ancestor is not a real directory"); }
async function bounded(root: string, ref: string, limit = 32 * 1024 * 1024): Promise<Buffer> { if (!safeRef(ref) || !inside(root, join(root, ref))) fail("unsafe reference"); let current = resolve(root); for (const part of ref.split("/")) { current = join(current, part); const s = await lstat(current).catch(() => undefined); if (s?.isSymbolicLink()) fail("symbolic link"); } const s = await lstat(join(root, ref)).catch(() => undefined); if (!s?.isFile() || s.isSymbolicLink() || s.size > limit) fail("unreadable artifact"); const h = await open(join(root, ref), "r"); try { const before = await h.stat(); const b = Buffer.alloc(before.size); let n = 0; while (n < b.length) { const x = await h.read(b, n, b.length - n, null); if (!x.bytesRead) break; n += x.bytesRead; } const after = await h.stat(); if (n !== b.length || after.size !== before.size) fail("artifact changed while reading"); return b; } finally { await h.close(); } }
function parseJson(bytes: Buffer): unknown { try { return JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(bytes)); } catch { fail("invalid UTF-8 or JSON"); } }
function assertPublic(value: unknown): void { if (typeof value === "string") { if (isAbsolute(value) || value.includes("\\") || value.includes("\0") || value.split("/").some(p => p === "..") || value.startsWith("file:") || value.includes("/Users/") || value.includes("/private/") || value.includes("/tmp/")) fail("unsafe public value"); return; } if (Array.isArray(value)) value.forEach(assertPublic); else if (value && typeof value === "object") Object.values(value).forEach(assertPublic); }
async function exclusive(path: string, bytes: string | Uint8Array): Promise<void> { try { await writeFile(path, bytes, { flag: "wx", mode: 0o600 }); } catch (e) { if ((e as NodeJS.ErrnoException).code === "EEXIST") fail("explanation already exists"); throw e; } }
function records(result: InstructionImpactResult, direction?: string, classification?: string): unknown[] { return result.records.filter(r => (direction ? r.impact.direction === direction : true) && (classification ? r.alignment.classification === classification : true)); }
export function renderExplanationReport(summary: Json): string { const section = (title: string, value: unknown) => `## ${title}\n${Array.isArray(value) && value.length ? value.map(x => `- ${typeof x === "string" ? x : JSON.stringify(x)}`).join("\n") : `- ${String(value ?? "none")}\n`}\n`; return `# Explanation\n\n## Experiment\n- Status: ${summary.status}\n- Experiment: ${summary.experimentId}\n\n${section("Evidence status", summary.evidenceStatus)}${section("helped", summary.helped)}${section("hurt", summary.hurt)}${section("stale", summary.stale)}${section("irrelevant", summary.irrelevant)}${section("conflicting", summary.conflicting)}${section("neutral/not-applied", summary.neutralOrNotApplied)}${section("unresolved", summary.unresolved)}${section("token/runtime observations", summary.tokenRuntimeObservations)}${section("change-focus", summary.changeFocus)}${section("evidence refs", summary.evidenceRefs)}${section("contradicting evidence", summary.contradictingEvidence)}${section("limitations", summary.limitations)}${section("simulation disclaimer", summary.simulationDisclaimer)}`; }
function makeSummary(experimentId: string, status: string, result: InstructionImpactResult): Json { const ids = (x: unknown[]) => x.map(v => (v as any).instruction.instructionId).sort(); return { experimentId, status, evidenceStatus: status === "valid" ? "complete" : status === "limited" ? "bounded partial; causality is not definitive" : "invalid evidence; no impact attribution", helped: ids(records(result, "helped")), hurt: ids(records(result, "hurt")), stale: ids(records(result, undefined, "stale")), irrelevant: ids(records(result, undefined, "irrelevant")), conflicting: ids(records(result, undefined, "conflicting")), neutralOrNotApplied: ids(result.records.filter(r => r.impact.direction === "neutral" || r.alignment.classification === "not-applied")), unresolved: ids(result.records.filter(r => r.impact.direction === "unknown" || r.analysisStatus === "unresolved")), tokenRuntimeObservations: ["Measurements are observations, not instruction causality."], changeFocus: ["Change linkage is reported only as bounded evidence."], evidenceRefs: result.records.flatMap(r => r.evidence.map(e => e.sourceRef)).filter(safeRef).sort(), contradictingEvidence: result.records.flatMap(r => r.evidence.filter(e => e.relation === "contradicting").map(e => e.sourceRef)).filter(safeRef).sort(), limitations: [...new Set(result.records.flatMap(r => r.limitations))].sort(), simulationDisclaimer: "This artifact explains validated evidence; it does not rerun an experiment or prove agent quality." }; }
function boundedResult(result: InstructionImpactResult, status: "valid" | "limited" | "invalid"): InstructionImpactResult { if (status === "valid") return result; return { ...result, records: result.records.map(r => ({ ...r, impact: { ...r.impact, direction: "unknown", explanation: status === "invalid" ? "Invalid evidence prevents impact attribution." : "Limited evidence does not support definitive causality." }, limitations: [...new Set([...r.limitations, status === "invalid" ? "Invalid evidence; no helped or harmful attribution is published." : "Limited evidence; helped or harmful attribution is withheld."])], analysisStatus: status })) }; }
export async function writeExplanationArtifacts(runDirectory: string, experimentId: string, status: "valid" | "limited" | "invalid", result: InstructionImpactResult): Promise<ExplanationArtifacts> { result = boundedResult(result, status); validateInstructionEvidenceBundle(result); assertPublic(result); await realDirectory(runDirectory); const final = join(runDirectory, "explanation"); const existing = await lstat(final).catch(() => undefined); if (existing) fail("explanation already exists"); const summary = makeSummary(experimentId, status, result); assertPublic(summary); const files: Array<[string, string, string]> = [["instruction-impacts.json", canonicalJson(result), "impact"], ["helped-instructions.json", canonicalJson({ schemaVersion: result.schemaVersion, records: records(result, "helped") }), "helped"], ["harmful-instructions.json", canonicalJson({ schemaVersion: result.schemaVersion, records: records(result, "hurt") }), "harmful"], ["unresolved-instructions.json", canonicalJson({ schemaVersion: result.schemaVersion, records: records(result, "unknown") }), "unresolved"], ["explanation-summary.json", canonicalJson(summary), "summary"]]; const temp = join(runDirectory, `.explanation-${process.pid}-${Date.now()}`); await mkdir(temp, { recursive: false, mode: 0o700 }); try { for (const [name, bytes] of files) await exclusive(join(temp, name), bytes); const report = renderExplanationReport(summary); await exclusive(join(temp, "REPORT.md"), report); const entries: ExplanationIndexEntry[] = []; for (const [name, , kind] of [...files, ["REPORT.md", report, "report"] as [string, string, string]]) { const b = await readFile(join(temp, name)); entries.push({ relativePath: `explanation/${name}`, kind, sha256: sha256(b), byteLength: b.length }); } entries.sort((a, b) => a.relativePath.localeCompare(b.relativePath)); const index: ExplanationEvidenceIndex = { schemaVersion: "s7-03.1", experimentId, entries, aggregateHash: sha256(canonicalJson(entries)) }; await exclusive(join(temp, EXPLANATION_INDEX), canonicalJson(index)); await rename(temp, final); return { directory: final, index, result, summary, report }; } catch (e) { await rm(temp, { recursive: true, force: true }); throw e; } }
export async function validateExplanationArtifacts(runDirectory: string, expectedExperimentId?: string): Promise<ExplanationArtifacts> { const root = resolve(runDirectory); await realDirectory(root); const idx = parseJson(await bounded(root, "explanation/evidence-index.json")) as ExplanationEvidenceIndex; assertPublic(idx); if (idx.schemaVersion !== "s7-03.1" || !Array.isArray(idx.entries) || (expectedExperimentId !== undefined && idx.experimentId !== expectedExperimentId)) fail("invalid index"); if (idx.entries.length !== 6 || idx.entries.some(e => !safeRef(e.relativePath) || !e.relativePath.startsWith("explanation/") || e.relativePath === "explanation/evidence-index.json")) fail("invalid entries"); const sorted = [...idx.entries].sort((a,b) => a.relativePath.localeCompare(b.relativePath)); if (canonicalJson(idx.entries) !== canonicalJson(sorted)) fail("non-canonical index order"); for (const e of idx.entries) { const b = await bounded(root, e.relativePath); if (b.length !== e.byteLength || sha256(b) !== e.sha256) fail("artifact hash or length mismatch"); } if (sha256(canonicalJson(idx.entries)) !== idx.aggregateHash) fail("aggregate hash mismatch"); const impact = validateInstructionEvidenceBundle(parseJson(await bounded(root, "explanation/instruction-impacts.json"))) as InstructionImpactResult; const summary = parseJson(await bounded(root, "explanation/explanation-summary.json")) as Json; assertPublic(impact); assertPublic(summary); const reportBytes = await bounded(root, "explanation/REPORT.md"); let report: string; try { report = new TextDecoder("utf-8", { fatal: true }).decode(reportBytes); } catch { fail("invalid report UTF-8"); } if (report !== renderExplanationReport(summary)) fail("report mismatch"); return { directory: join(root, "explanation"), index: idx, result: impact, summary, report }; }
function publicArtifactRef(runDirectory: string, value: unknown, fallback: string): string { if (typeof value !== "string" || value.length === 0) return fallback; const candidate = resolve(value); const rel = relative(resolve(runDirectory), candidate); if (rel !== "" && rel !== ".." && !rel.startsWith(`..${sep}`) && !isAbsolute(rel)) return rel.split(sep).join("/"); return fallback; }
async function persistedJson(runDirectory: string, controllerRoot: string, value: unknown, fallback: string): Promise<{ value: unknown; ref: string } | undefined> { if (typeof value !== "string" || value.length === 0) return undefined; const absolute = isAbsolute(value); const readRoot = absolute ? resolve(controllerRoot) : resolve(runDirectory); const candidate = absolute ? resolve(value) : resolve(runDirectory, value); const rel = relative(readRoot, candidate); if (rel === ".." || rel.startsWith(`..${sep}`) || isAbsolute(rel) || rel.includes("\\")) return undefined; const ref = absolute ? fallback : rel.split(sep).join("/"); try { const bytes = await bounded(readRoot, rel.split(sep).join("/"), 8 * 1024 * 1024); return { value: parseJson(bytes), ref }; } catch { return undefined; } }
function explicitRecords(value: unknown, ref: string, condition: string): Array<Record<string, unknown>> { const found: Array<Record<string, unknown>> = []; const visit = (v: unknown): void => { if (Array.isArray(v)) { v.forEach(visit); return; } if (!v || typeof v !== "object") return; const o = v as Record<string, unknown>; const candidateId = typeof o.candidateId === "string" ? o.candidateId : typeof o.instructionId === "string" ? o.instructionId : undefined; if (candidateId !== undefined && Object.keys(o).some(k => ["status", "result", "outcome", "kind", "dependency", "package", "path", "ruleId", "checkId", "requirementId", "sourceRef", "statement", "decision", "relevance", "intelligenceStatus", "conflictingCandidateIds", "excluded"].includes(k))) { const copy: Record<string, unknown> = { ...o, instructionId: candidateId, identity: typeof o.statement === "string" ? o.statement : (typeof o.identity === "string" ? o.identity : candidateId) }; copy.sourceRef = safeRef(copy.sourceRef) ? copy.sourceRef : ref; copy.conditionId = condition; found.push(copy); } Object.values(o).forEach(visit); }; visit(value); return found; }
export async function deriveExplanationInput(verified: any): Promise<InstructionImpactInput> { const r = verified.experiment ?? verified; const runDirectory = resolve(verified.experimentDirectory ?? "."); const marker = `${sep}.camarade${sep}runs${sep}`; const markerIndex = runDirectory.indexOf(marker); const controllerRoot = markerIndex >= 0 ? runDirectory.slice(0, markerIndex) : runDirectory; const contexts = Array.isArray(r.manifest?.conditionContextManifests) ? r.manifest.conditionContextManifests : []; const byCondition: Record<string, Record<string, unknown>[]> = { baseline: [], camarade: [] }; const evidenceByCondition: Record<string, Record<string, unknown>> = { baseline: {}, camarade: {} }; const persistedFacts: Record<string, unknown>[] = []; const instructions: Record<string, unknown>[] = []; for (const context of contexts) { const condition = String(context.conditionId ?? "unknown"); const sources = Array.isArray(context.sources) ? context.sources : []; for (const [index, source] of sources.entries()) { const hash = typeof source.contentHash === "string" && /^[a-f0-9]{64}$/u.test(source.contentHash) ? source.contentHash : sha256(`${condition}:${index}`); const leaf = typeof source.relativePath === "string" ? source.relativePath.split(/[\\/]/).pop() : `source-${index + 1}`; const safeLeaf = (leaf ?? `source-${index + 1}`).replace(/[^A-Za-z0-9._-]/g, "_"); const id = `instruction-${hash.slice(0, 16)}`; const record = { instructionId: id, identity: `${condition}:${safeLeaf}`, sourceRef: `stage-4/${condition}/${safeLeaf}`, sourceHash: hash, included: condition === "camarade" }; instructions.push(record); if (byCondition[condition]) byCondition[condition].push(record); }
    const paths = Array.isArray(context.stage4ArtifactPaths) ? context.stage4ArtifactPaths : []; for (const [index, path] of paths.entries()) { const loaded = await persistedJson(runDirectory, controllerRoot, path, `stage-4/${condition}/artifact-${index + 1}.json`); if (!loaded) continue; const recordsFound = explicitRecords(loaded.value, loaded.ref, condition); const bucket = evidenceByCondition[condition]; if (bucket) { for (const record of recordsFound) { const key = typeof record.dependency === "string" || typeof record.package === "string" ? "dependencyEvidence" : typeof record.checkId === "string" ? "checkResults" : typeof record.ruleId === "string" || String(record.kind).includes("rule") ? "ruleResults" : typeof record.requirementId === "string" ? "requirementResults" : "changes"; const current = Array.isArray(bucket[key]) ? bucket[key] as unknown[] : []; current.push(record); bucket[key] = current as unknown as Record<string, unknown>; } } persistedFacts.push(...recordsFound.filter(record => ["active-replacement", "replacement", "current-architecture"].includes(String(record.kind)))); }
  }
  const baseline = { ...(r.baseline ?? {}), instructions: byCondition.baseline, ...evidenceByCondition.baseline }; const optimized = { ...(r.camarade ?? {}), instructions: byCondition.camarade, ...evidenceByCondition.camarade }; const validations = r.validations ?? {}; const evidence = { baseline: { validations: validations.baseline, execution: r.baseline }, camarade: { validations: validations.camarade, execution: r.camarade } }; const taskScope = r.specification?.taskScope ?? r.specification?.relevance ?? r.manifest?.taskScope; return { instructions: instructions.length ? instructions : [{ instructionId: "persisted-context-unresolved", identity: "Persisted context evidence unavailable", sourceRef: "stage-4/unresolved.json", included: false }], baseline: { ...baseline, ...evidence.baseline }, optimized: { ...optimized, ...evidence.camarade }, repository: { facts: [...contexts.map((context: any) => ({ kind: "persisted-context", conditionId: context.conditionId, sourceRef: `stage-4/${context.conditionId}/manifest.json`, contextHash: context.contextHash })), ...persistedFacts], ...(taskScope === undefined ? {} : { taskScope }) }, ...(taskScope === undefined ? {} : { taskScope }), task: typeof r.specification?.task === "string" ? "persisted-task" : undefined, experimentStatus: verified.status }; }

export function normalizePersistedCandidateInput(input: InstructionImpactInput): InstructionImpactInput {
  const source = (input as unknown as Record<string, unknown>);
  const instructions = Array.isArray(input.instructions) ? [...input.instructions] as Record<string, unknown>[] : [];
  const byId = new Map(instructions.map(record => [String(record.instructionId ?? ""), record]));
  const facts: Record<string, unknown>[] = [];
  const irrelevant: Record<string, unknown>[] = [];
  const conditionValues: Array<["baseline" | "optimized", unknown]> = [["baseline", input.baseline], ["optimized", input.optimized]];
  for (const [condition, value] of conditionValues) {
    const container = value && typeof value === "object" ? { ...(value as Record<string, unknown>) } : {};
    const existing = Array.isArray(container.instructions) ? [...container.instructions] as Record<string, unknown>[] : [];
    const seen = new Set(existing.map(record => String(record.instructionId ?? "")));
    for (const records of Object.values(container)) {
      if (!Array.isArray(records)) continue;
      for (const raw of records) {
        if (!raw || typeof raw !== "object") continue;
        const record = raw as Record<string, unknown>;
        const id = typeof record.instructionId === "string" ? record.instructionId : undefined;
        if (!id || !record.identity) continue;
        const normalized = { instructionId: id, identity: String(record.identity), sourceRef: safeRef(record.sourceRef) ? record.sourceRef : `stage-4/${condition}/persisted.json`, sourceHash: typeof record.sourceHash === "string" ? record.sourceHash : undefined, included: record.included !== false };
        if (!byId.has(id)) { byId.set(id, normalized); instructions.push(normalized); }
        if (!seen.has(id)) { seen.add(id); existing.push(normalized); }
        if (record.intelligenceStatus === "stale" || record.intelligenceStatus === "unsupported" || record.conflictingCandidateIds !== undefined) facts.push({ ...record, conditionId: condition });
        const relevance = String(record.relevance ?? "").toLowerCase();
        if (record.excluded === true || String(record.decision ?? "").toLowerCase() === "exclude" || relevance === "none" || relevance === "task-irrelevant" || record.irrelevant === true) irrelevant.push({ instructionId: id, identity: normalized.identity, sourceRef: normalized.sourceRef });
      }
    }
    container.instructions = existing;
    if (condition === "baseline") source.baseline = container; else source.optimized = container;
  }
  const repository = source.repository && typeof source.repository === "object" ? { ...(source.repository as Record<string, unknown>) } : {};
  const oldFacts = Array.isArray(repository.facts) ? repository.facts as unknown[] : [];
  const uniqueFacts = [...oldFacts, ...facts].filter((fact, index, all) => all.findIndex(other => canonicalJson(other) === canonicalJson(fact)) === index);
  repository.facts = uniqueFacts;
  source.repository = repository;
  if (irrelevant.length) source.taskScope = { ...(source.taskScope as Record<string, unknown> ?? {}), irrelevantInstructions: irrelevant.filter((record, index, all) => all.findIndex(other => other.instructionId === record.instructionId) === index) };
  source.instructions = instructions;
  return source as unknown as InstructionImpactInput;
}
